-- ============================================================================
-- Monolith POS — Full Schema Export (Multi-Schema + Public Views)
-- ============================================================================
-- For a NEW Supabase project. Run in SQL Editor.
--
-- Tables live in domain schemas for clean organization.
-- Thin updatable views in "public" keep the Supabase JS client working
-- with zero frontend code changes (except realtime schema params).
--
-- Schemas: menu, orders, tables, staff, tickets, advance, analytics, events
-- ============================================================================

-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  0. CREATE SCHEMAS & EXPOSE TO PostgREST                               ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE SCHEMA IF NOT EXISTS menu;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS tables;
CREATE SCHEMA IF NOT EXISTS staff;
CREATE SCHEMA IF NOT EXISTS tickets;
CREATE SCHEMA IF NOT EXISTS advance;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS events;

-- Grant USAGE so anon/authenticated can access these schemas
GRANT USAGE ON SCHEMA menu       TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA orders     TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA tables     TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA staff      TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA tickets    TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA advance    TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA analytics  TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA events     TO anon, authenticated, service_role;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  1. TABLES SCHEMA — Physical dining tables & layout                    ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS tables."Restaurant_Tables" (
    "TABLE_ID"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TABLE_NUM"            bigint NOT NULL DEFAULT 0,
    "STATUS"               text NULL,
    "GUEST_CAPACITY"       bigint NULL DEFAULT 0,
    "CURRENT_GUEST_COUNT"  bigint NULL DEFAULT 0,
    "RESERVED_SINCE"       timestamp without time zone NULL,
    "BILL_OUT_REQUESTED"   boolean NULL DEFAULT false,
    "MERGE_GROUP_ID"       bigint NULL DEFAULT NULL,
    "RESERVATION_NAME"     text NULL DEFAULT NULL,
    "RESERVATION_PAX"      bigint NULL DEFAULT NULL,
    "RESERVATION_NOTES"    text NULL DEFAULT NULL,
    "IS_MERGE_MEMBER"      boolean NULL DEFAULT false,
    "IS_MERGE_CAPTAIN"     boolean NULL DEFAULT false,
    -- From migration 018 (newer than CSV):
    "LAYOUT_X"             integer NULL DEFAULT NULL,
    "LAYOUT_Y"             integer NULL DEFAULT NULL,
    CONSTRAINT "Restaurant_Tables_pkey" PRIMARY KEY ("TABLE_ID"),
    CONSTRAINT restaurant_tables_status_check CHECK (
        "STATUS" = ANY (ARRAY[
            'AVAILABLE'::text, 'RESERVED'::text, 'OCCUPIED'::text,
            'HAS_REQUEST'::text, 'UNAVAILABLE'::text
        ])
    )
);

-- Self-referencing FK for merged tables
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'restaurant_tables_merge_group_fkey') THEN
        ALTER TABLE tables."Restaurant_Tables"
        ADD CONSTRAINT restaurant_tables_merge_group_fkey
        FOREIGN KEY ("MERGE_GROUP_ID") REFERENCES tables."Restaurant_Tables" ("TABLE_ID") ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS tables."Table_Reservations" (
    "RESERVATION_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TABLE_ID"          bigint NOT NULL REFERENCES tables."Restaurant_Tables"("TABLE_ID") ON DELETE CASCADE,
    "APPOINTED_NAME"    text NULL,
    "GUEST_COUNT"       bigint NULL,
    "RESERVATION_NOTE"  text NULL,
    "TIME_LIMIT"        time without time zone NULL
);

CREATE TABLE IF NOT EXISTS tables."Table_Layout_Presets" (
    "PRESET_ID"             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "PRESET_NAME"           text NOT NULL,
    "DESCRIPTION"           text NULL DEFAULT NULL,
    "FLOOR_WIDTH_BLOCKS"    integer NOT NULL DEFAULT 20,
    "FLOOR_HEIGHT_BLOCKS"   integer NOT NULL DEFAULT 16,
    "TABLE_SIZE_BLOCKS"     integer NOT NULL DEFAULT 2,
    "TABLE_SPACING_BLOCKS"  integer NOT NULL DEFAULT 1,
    "SNAP_TO_GRID"          boolean NOT NULL DEFAULT true,
    "LAYOUT_DATA"           jsonb NOT NULL DEFAULT '[]'::jsonb,
    "MERGE_GROUPS"          jsonb NULL DEFAULT '[]'::jsonb,
    "IS_ACTIVE"             boolean NOT NULL DEFAULT false,
    "CREATED_AT"            timestamptz NOT NULL DEFAULT now(),
    "UPDATED_AT"            timestamptz NOT NULL DEFAULT now(),
    "CREATED_BY"            text NULL DEFAULT NULL,
    "EVENT_ID"              bigint NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS tables."Custom_Table_Templates" (
    "TEMPLATE_ID"    text PRIMARY KEY,
    "LABEL"          text NOT NULL,
    "SEATS"          integer NOT NULL CHECK ("SEATS" > 0),
    "WIDTH_BLOCKS"   integer NOT NULL DEFAULT 2,
    "HEIGHT_BLOCKS"  integer NOT NULL DEFAULT 2,
    "IS_CUSTOM"      boolean NOT NULL DEFAULT true,
    "CREATED_AT"     timestamptz NOT NULL DEFAULT now(),
    "UPDATED_AT"     timestamptz NOT NULL DEFAULT now()
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  2. MENU SCHEMA — Categories, items, groups                            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS menu."Menu_Categories" (
    "CATEGORY_ID"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CATEGORY_NAME"        text NOT NULL,
    "CATEGORY_ITEM_COUNT"  bigint NULL DEFAULT 0,
    "CATEGORY_ICON"        text NULL
);

CREATE TABLE IF NOT EXISTS menu."Menu_Items" (
    "ITEM_ID"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CATEGORY_ID"        bigint NOT NULL REFERENCES menu."Menu_Categories"("CATEGORY_ID") ON DELETE SET NULL,
    "ITEM_NAME"          text NULL,
    "ITEM_DESCRIPTION"   text NULL,
    "ITEM_PRICE"         double precision NULL,
    "ITEM_IMAGE_URL"     text NULL,
    "ITEM_STATUS"        text NULL DEFAULT 'AVAILABLE'::text,
    "MENU_ITEM_DIETARY"  text NULL,
    "ORDER_LIMIT"        bigint NULL DEFAULT 0,
    CONSTRAINT menu_items_status_check CHECK (
        "ITEM_STATUS" = ANY (ARRAY['AVAILABLE'::text, 'OUT_OF_STOCK'::text])
    )
);

CREATE TABLE IF NOT EXISTS menu."Menu_Item_Groups" (
    "MENU_GROUP_ID"       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GROUP_NAME"          text NULL,
    "GROUP_DESCRIPTION"   text NULL,
    "GROUP_PRICE"         double precision NULL,
    "GROUP_IMAGE_URL"     text NULL,
    "GROUP_STATUS"        text NULL,
    "GROUP_ORDER_LIMIT"   bigint NULL,
    "CATEGORY_ID"         bigint NULL REFERENCES menu."Menu_Categories"("CATEGORY_ID") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS menu."Item_Groups" (
    "ID"              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MENU_GROUP_ID"   bigint NOT NULL REFERENCES menu."Menu_Item_Groups"("MENU_GROUP_ID") ON DELETE CASCADE,
    "ITEM_ID"         bigint NULL REFERENCES menu."Menu_Items"("ITEM_ID") ON DELETE CASCADE
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  3. ORDERS SCHEMA — Dine-in order lifecycle                            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS orders."Restaurant_Orders" (
    "ORDER_ID"        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TABLE_ID"        bigint NOT NULL REFERENCES tables."Restaurant_Tables"("TABLE_ID") ON DELETE CASCADE,
    "REQUESTED_FROM"  text NULL DEFAULT 'None'::text,
    "ORDER_TYPE"      text NULL DEFAULT 'Dine-in'::text,
    "ORDER_STATUS"    text NULL DEFAULT 'Pending'::text,
    "SUBTOTAL_BILL"   double precision NULL DEFAULT 0,
    "TOTAL_BILL"      double precision NULL DEFAULT 0,
    "TIME"            timestamp without time zone NULL,
    "KITCHEN_NOTE"    text NULL,
    "SERVER_NOTE"     text NULL,
    "GUEST_COUNT"     integer NULL DEFAULT 1,
    "READY_AT"        timestamp without time zone NULL,
    "SERVED_AT"       timestamp without time zone NULL,
    "COMPLETED_AT"    timestamp without time zone NULL,
    "PAYMENT_METHOD"  text NULL DEFAULT 'CASH'::text,
    CONSTRAINT "Restaurant_Orders_pkey" PRIMARY KEY ("ORDER_ID"),
    CONSTRAINT "Restaurant_Orders_ORDER_ID_key" UNIQUE ("ORDER_ID"),
    CONSTRAINT restaurant_orders_requested_from_check CHECK (
        "REQUESTED_FROM" = ANY (ARRAY['Cashier'::text, 'Customer'::text])
    ),
    CONSTRAINT restaurant_orders_order_type_check CHECK (
        "ORDER_TYPE" = ANY (ARRAY['DINE-IN'::text, 'TAKEOUT'::text])
    ),
    CONSTRAINT restaurant_orders_order_status_check CHECK (
        "ORDER_STATUS" = ANY (ARRAY[
            'REQUESTED'::text, 'VERIFIED'::text, 'PREPARING'::text,
            'READY'::text, 'SERVED'::text, 'CANCELLED'::text, 'COMPLETED'::text
        ])
    )
);

ALTER TABLE orders."Restaurant_Orders" REPLICA IDENTITY FULL;

CREATE TABLE IF NOT EXISTS orders."Order_Items" (
    "ORDER_ITEM_ID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ORDER_ID"           bigint NOT NULL REFERENCES orders."Restaurant_Orders"("ORDER_ID") ON DELETE CASCADE,
    "ITEM_ID"            bigint NULL REFERENCES menu."Menu_Items"("ITEM_ID") ON DELETE SET NULL,
    "DISCOUNT_ID"        bigint NULL,
    "ORDER_ITEM_STATUS"  text NULL DEFAULT 'PENDING'::text,
    "IS_FLAGGED"         boolean NULL,
    "REJECTION_REASON"   text[] NULL,
    -- From migration (newer):
    "NOTES"              text NULL,
    CONSTRAINT order_items_status_check CHECK (
        "ORDER_ITEM_STATUS" = ANY (ARRAY['PENDING'::text, 'COOKING'::text, 'DONE'::text, 'CANCELLED'::text])
    )
);

ALTER TABLE orders."Order_Items" REPLICA IDENTITY FULL;

CREATE TABLE IF NOT EXISTS orders."Discounts" (
    "DISCOUNT_ID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ORDER_ID"         bigint NOT NULL REFERENCES orders."Restaurant_Orders"("ORDER_ID") ON DELETE CASCADE,
    "ORDER_ITEM_ID"    bigint NULL REFERENCES orders."Order_Items"("ORDER_ITEM_ID") ON DELETE CASCADE,
    "PWD"              boolean NULL DEFAULT false,
    "PWD_AMOUNT"       bigint NULL DEFAULT 0,
    "SENIOR"           boolean NULL DEFAULT false,
    "SENIOR_AMOUNT"    bigint NULL DEFAULT 0,
    "CUSTOM_PERCENT"   bigint NULL DEFAULT 0,
    "PESO_DISCOUNT"    double precision NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders."Bill_Requests" (
    "REQUEST_ID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TABLE_ID"        bigint NOT NULL,
    "ORDER_ID"        bigint NULL,
    "PAYMENT_METHOD"  text NOT NULL,
    "STATUS"          text NOT NULL DEFAULT 'REQUESTED'::text,
    "REQUESTED_AT"    timestamp without time zone NULL DEFAULT now(),
    CONSTRAINT bill_requests_payment_check CHECK (
        "PAYMENT_METHOD" = ANY (ARRAY['CASH'::text, 'CREDIT_CARD'::text, 'INSTAPAY_QR'::text])
    ),
    CONSTRAINT bill_requests_status_check CHECK (
        "STATUS" = ANY (ARRAY['REQUESTED'::text, 'PROCESSING'::text, 'PAID'::text, 'CANCELLED'::text])
    )
);

CREATE TABLE IF NOT EXISTS orders."Order_Events" (
    "EVENT_ID"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ORDER_ID"         bigint NOT NULL REFERENCES orders."Restaurant_Orders"("ORDER_ID") ON DELETE CASCADE,
    "EVENT_TYPE"       text NOT NULL,
    "PREVIOUS_STATUS"  text NULL,
    "NEW_STATUS"       text NOT NULL,
    "TIMESTAMP"        timestamp without time zone NULL DEFAULT now(),
    "ACTOR"            text NULL,
    "REASON"           text NULL,
    "METADATA"         jsonb NULL
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  4. STAFF SCHEMA                                                       ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS staff."Staff_Accounts" (
    "ACCOUNT_ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AUTH_USER_ID"  uuid NULL,
    "FULL_NAME"     text NOT NULL,
    "EMAIL"         text NOT NULL UNIQUE,
    "ROLE"          text NOT NULL DEFAULT 'STAFF'::text,
    "STATUS"        text NOT NULL DEFAULT 'ACTIVE'::text,
    "PERMISSIONS"   text[] NOT NULL DEFAULT ARRAY[]::text[],
    "PHONE"         text NULL,
    "NOTES"         text NULL,
    "CREATED_AT"    timestamptz NOT NULL DEFAULT now(),
    "UPDATED_AT"    timestamptz NOT NULL DEFAULT now(),
    "LAST_LOGIN"    timestamptz NULL,
    CONSTRAINT staff_accounts_role_check CHECK (
        "ROLE" = ANY (ARRAY['ADMIN'::text, 'MANAGER'::text, 'CASHIER'::text, 'KITCHEN'::text, 'STAFF'::text])
    ),
    CONSTRAINT staff_accounts_status_check CHECK (
        "STATUS" = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text, 'SUSPENDED'::text])
    )
);

CREATE TABLE IF NOT EXISTS staff."Staff_Codes" (
    "CODE_ID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "STAFF_NAME"   text NOT NULL,
    "STAFF_ROLE"   text NULL,
    "STATUS"       text NOT NULL DEFAULT 'ACTIVE'::text,
    CONSTRAINT staff_codes_status_check CHECK (
        "STATUS" = ANY (ARRAY['ACTIVE'::text, 'INACTIVE'::text, 'SUSPENDED'::text])
    )
);

CREATE TABLE IF NOT EXISTS staff."Cashier_Staff" (
    "CASHIER_ID"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "STAFF_ID"              bigint NOT NULL,
    "TOTAL_SHIFT_EARNING"   double precision NULL,
    "TOTAL_TABLES_HANDLED"  bigint NULL
);

CREATE TABLE IF NOT EXISTS staff."Dispatcher_Staff" (
    "DISPATCHER_ID"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "STAFF_ID"                 bigint NOT NULL,
    "CURRENT_DISPATCHED_MEALS" bigint NULL,
    "TOTAL_DISPATCHED_MEALS"   bigint NULL
);

CREATE TABLE IF NOT EXISTS staff."Superviser_Staff" (
    "SUPERVISER_CODE"  bigint NOT NULL PRIMARY KEY,
    "STAFF_ID"         timestamptz NOT NULL DEFAULT now()
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  5. TICKETS SCHEMA — Counter/ticket ordering                           ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS tickets."Ticket_Orders" (
    "TICKET_ID"                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "REGISTERED_NAME"              text NULL,
    "REGISTERED_CONTACT_INFO"      bigint NULL,
    "REGISTERED_TIME_OF_ARRIVAL"   time without time zone NULL,
    "TICKET_STATUS"                text NULL,
    -- From migrations (newer):
    "TICKET_NUM"                   integer NULL,
    "ORDER_TYPE"                   text NULL DEFAULT 'DINE-IN'::text,
    "TOTAL_BILL"                   double precision NULL DEFAULT 0,
    "TIME"                         timestamp without time zone NULL DEFAULT now(),
    "CREATED_AT"                   timestamptz NOT NULL DEFAULT now(),
    "COMPLETED_AT"                 timestamptz NULL,
    CONSTRAINT ticket_orders_status_check CHECK (
        "TICKET_STATUS" = ANY (ARRAY['REQUESTED'::text, 'PREPARING'::text, 'COMPLETED'::text])
    )
);

CREATE TABLE IF NOT EXISTS tickets."Ticket_Order_Items" (
    "TICKET_ORDER_ITEM_ID"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TICKET_ORDER_ID"             bigint NOT NULL REFERENCES tickets."Ticket_Orders"("TICKET_ID") ON DELETE CASCADE,
    "ITEM_ID"                     bigint NULL REFERENCES menu."Menu_Items"("ITEM_ID") ON DELETE SET NULL,
    "DISCOUNT_ID"                 bigint NULL,
    "TICKET_ORDER_ITEM_STATUS"    text NULL,
    "ITEM_GROUP_ID"               bigint NULL REFERENCES menu."Menu_Item_Groups"("MENU_GROUP_ID") ON DELETE SET NULL,
    -- From migrations (newer):
    "ITEM_NAME"                   text NULL,
    "ITEM_PRICE"                  double precision NULL DEFAULT 0,
    "NOTES"                       text NULL,
    CONSTRAINT ticket_order_items_status_check CHECK (
        "TICKET_ORDER_ITEM_STATUS" = ANY (ARRAY['REQUESTED'::text, 'PREPARING'::text, 'COMPLETED'::text])
    )
);

CREATE TABLE IF NOT EXISTS tickets."Ticket_Order_Group_Items" (
    "TICKET_ORDER_GROUP_ITEM_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TICKET_GROUP_ID"             bigint NOT NULL UNIQUE
        REFERENCES tickets."Ticket_Order_Items"("TICKET_ORDER_ITEM_ID") ON DELETE CASCADE,
    "ITEM_ID"                     bigint NULL REFERENCES menu."Menu_Items"("ITEM_ID") ON DELETE SET NULL,
    "ITEM_STATUS"                 text NULL,
    -- From migrations (newer):
    "ITEM_NAME"                   text NULL,
    "ITEM_PRICE"                  double precision NULL DEFAULT 0,
    CONSTRAINT ticket_group_items_status_check CHECK (
        "ITEM_STATUS" = ANY (ARRAY['REQUESTED'::text, 'PREPARING'::text, 'COMPLETED'::text])
    )
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  6. ADVANCE SCHEMA — Pre-arrival ordering                              ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS advance."Advance_Orders" (
    "ADVANCE_ORDER_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ORDER_NUMBER"      text NOT NULL UNIQUE,
    "SESSION_TOKEN"     text NOT NULL UNIQUE,
    "CUSTOMER_NAME"     text NOT NULL,
    "DINING_TYPE"       text NOT NULL DEFAULT 'dine-in'::text,
    "STATUS"            text NOT NULL DEFAULT 'PENDING'::text,
    "SUBTOTAL"          numeric(10,2) NOT NULL DEFAULT 0.00,
    "TOTAL_AMOUNT"      numeric(10,2) NOT NULL DEFAULT 0.00,
    "NOTES"             text NULL,
    "CREATED_AT"        timestamptz NOT NULL DEFAULT now(),
    "EXPIRES_AT"        timestamptz NOT NULL DEFAULT (now() + INTERVAL '30 minutes'),
    "CONFIRMED_AT"      timestamptz NULL,
    "COMPLETED_AT"      timestamptz NULL,
    "CANCELLED_AT"      timestamptz NULL,
    "TABLE_ID"          bigint NULL REFERENCES tables."Restaurant_Tables"("TABLE_ID") ON DELETE SET NULL,
    "TABLE_NUM"         integer NULL,
    CONSTRAINT advance_orders_dining_type_check CHECK (
        "DINING_TYPE" = ANY (ARRAY['dine-in'::text, 'take-away'::text])
    ),
    CONSTRAINT advance_orders_status_check CHECK (
        "STATUS" = ANY (ARRAY[
            'PENDING'::text, 'CONFIRMED'::text, 'PREPARING'::text,
            'READY'::text, 'COMPLETED'::text, 'CANCELLED'::text, 'EXPIRED'::text
        ])
    )
);

CREATE TABLE IF NOT EXISTS advance."Advance_Order_Items" (
    "ADVANCE_ITEM_ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ADVANCE_ORDER_ID"  bigint NOT NULL REFERENCES advance."Advance_Orders"("ADVANCE_ORDER_ID") ON DELETE CASCADE,
    "ITEM_ID"           bigint NOT NULL REFERENCES menu."Menu_Items"("ITEM_ID"),
    "ITEM_NAME"         text NOT NULL,
    "QUANTITY"          integer NOT NULL DEFAULT 1 CHECK ("QUANTITY" > 0),
    "UNIT_PRICE"        numeric(10,2) NOT NULL,
    "TOTAL_PRICE"       numeric(10,2) NOT NULL,
    "NOTES"             text NULL,
    "CREATED_AT"        timestamptz NOT NULL DEFAULT now()
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  7. ANALYTICS SCHEMA — Historical archive                              ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS analytics."Completed_Orders" (
    "ORDER_ID"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ORIGINAL_ORDER_ID" bigint NULL,
    "TABLE_ID"          bigint NULL,
    "TABLE_NUM"         int NULL,
    "ORDER_TYPE"        text NOT NULL DEFAULT 'DINE-IN',
    "REQUESTED_FROM"    text NOT NULL DEFAULT 'Cashier',
    "ORDER_STATUS"      text NOT NULL DEFAULT 'COMPLETED',
    "GUEST_COUNT"       int NOT NULL DEFAULT 1,
    "ITEM_COUNT"        int NOT NULL DEFAULT 0,
    "SUBTOTAL_BILL"     double precision NOT NULL DEFAULT 0,
    "TOTAL_BILL"        double precision NOT NULL DEFAULT 0,
    "DISCOUNT_AMOUNT"   double precision NOT NULL DEFAULT 0,
    "PAYMENT_METHOD"    text NOT NULL DEFAULT 'CASH',
    "TIME"              timestamp without time zone NOT NULL DEFAULT now(),
    "READY_AT"          timestamp without time zone NULL,
    "SERVED_AT"         timestamp without time zone NULL,
    "COMPLETED_AT"      timestamp without time zone NULL,
    "KITCHEN_NOTE"      text NULL,
    "SERVER_NOTE"       text NULL,
    "ORDER_ITEMS"       jsonb NOT NULL DEFAULT '[]'::jsonb
);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  8. EVENTS SCHEMA                                                      ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS events."Restaurant_Events" (
    "EVENT_ID"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TITLE"               text NOT NULL,
    "DESCRIPTION"         text NULL,
    "CATEGORY"            text NOT NULL DEFAULT 'Other'::text,
    "COLOR"               text NULL,
    "START_AT"            timestamptz NOT NULL,
    "END_AT"              timestamptz NOT NULL,
    "LOCATION"            text NULL,
    "ORGANIZER"           text NULL,
    "EXPECTED_ATTENDEES"  integer NULL CHECK ("EXPECTED_ATTENDEES" IS NULL OR "EXPECTED_ATTENDEES" >= 0),
    "CONTACT_NAME"        text NULL,
    "CONTACT_PHONE"       text NULL,
    "CONTACT_EMAIL"       text NULL,
    "NOTES"               text NULL,
    "IS_CANCELLED"        boolean NOT NULL DEFAULT false,
    "CREATED_BY"          text NULL,
    "CREATED_AT"          timestamptz NOT NULL DEFAULT now(),
    "UPDATED_AT"          timestamptz NOT NULL DEFAULT now(),
    "UPDATED_BY"          text NULL,
    "DELETED_AT"          timestamptz NULL,
    -- From migration 019 (newer):
    "PRESET_ID"           bigint NULL DEFAULT NULL,
    CONSTRAINT events_end_after_start CHECK ("END_AT" >= "START_AT"),
    CONSTRAINT events_category_check CHECK (
        "CATEGORY" = ANY (ARRAY[
            'Private Event', 'Birthday', 'Corporate Event', 'Meeting',
            'Reservation', 'Catering', 'Promotion', 'Holiday', 'Other'
        ]::text[])
    )
);

-- Cross-references: Events <-> Layout Presets
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_restaurant_events_preset') THEN
        ALTER TABLE events."Restaurant_Events"
            ADD CONSTRAINT fk_restaurant_events_preset
            FOREIGN KEY ("PRESET_ID") REFERENCES tables."Table_Layout_Presets"("PRESET_ID") ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_table_layout_presets_event') THEN
        ALTER TABLE tables."Table_Layout_Presets"
            ADD CONSTRAINT fk_table_layout_presets_event
            FOREIGN KEY ("EVENT_ID") REFERENCES events."Restaurant_Events"("EVENT_ID") ON DELETE SET NULL;
    END IF;
END $$;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  9. INDEXES                                                            ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- staff
CREATE INDEX IF NOT EXISTS idx_staff_accounts_email  ON staff."Staff_Accounts" ("EMAIL");
CREATE INDEX IF NOT EXISTS idx_staff_accounts_role   ON staff."Staff_Accounts" ("ROLE");
CREATE INDEX IF NOT EXISTS idx_staff_accounts_status ON staff."Staff_Accounts" ("STATUS");

-- orders
CREATE INDEX IF NOT EXISTS idx_restaurant_orders_time     ON orders."Restaurant_Orders" ("TIME" DESC);
CREATE INDEX IF NOT EXISTS idx_restaurant_orders_status   ON orders."Restaurant_Orders" ("ORDER_STATUS");
CREATE INDEX IF NOT EXISTS idx_restaurant_orders_table_id ON orders."Restaurant_Orders" ("TABLE_ID");
CREATE INDEX IF NOT EXISTS idx_order_events_order_id      ON orders."Order_Events" ("ORDER_ID", "TIMESTAMP" ASC);

-- events
CREATE INDEX IF NOT EXISTS idx_events_start_at   ON events."Restaurant_Events" ("START_AT");
CREATE INDEX IF NOT EXISTS idx_events_end_at     ON events."Restaurant_Events" ("END_AT");
CREATE INDEX IF NOT EXISTS idx_events_deleted    ON events."Restaurant_Events" ("DELETED_AT");
CREATE INDEX IF NOT EXISTS idx_events_cancelled  ON events."Restaurant_Events" ("IS_CANCELLED");
CREATE INDEX IF NOT EXISTS idx_events_preset_id  ON events."Restaurant_Events" ("PRESET_ID");

-- advance
CREATE INDEX IF NOT EXISTS idx_advance_orders_session_token ON advance."Advance_Orders" ("SESSION_TOKEN");
CREATE INDEX IF NOT EXISTS idx_advance_orders_order_number  ON advance."Advance_Orders" ("ORDER_NUMBER");
CREATE INDEX IF NOT EXISTS idx_advance_orders_status        ON advance."Advance_Orders" ("STATUS");
CREATE INDEX IF NOT EXISTS idx_advance_orders_expires_at    ON advance."Advance_Orders" ("EXPIRES_AT");
CREATE INDEX IF NOT EXISTS idx_advance_orders_table_id      ON advance."Advance_Orders" ("TABLE_ID");
CREATE INDEX IF NOT EXISTS idx_advance_order_items_order_id ON advance."Advance_Order_Items" ("ADVANCE_ORDER_ID");
CREATE INDEX IF NOT EXISTS idx_advance_order_items_item_id  ON advance."Advance_Order_Items" ("ITEM_ID");

-- tables
CREATE INDEX IF NOT EXISTS idx_layout_presets_active ON tables."Table_Layout_Presets" ("IS_ACTIVE") WHERE "IS_ACTIVE" = true;
CREATE INDEX IF NOT EXISTS idx_presets_event_id      ON tables."Table_Layout_Presets" ("EVENT_ID");

-- tickets
CREATE INDEX IF NOT EXISTS idx_ticket_orders_created_at ON tickets."Ticket_Orders" ("CREATED_AT");
CREATE INDEX IF NOT EXISTS idx_ticket_orders_status     ON tickets."Ticket_Orders" ("TICKET_STATUS");

-- analytics
CREATE INDEX IF NOT EXISTS idx_completed_orders_time         ON analytics."Completed_Orders" ("TIME" DESC);
CREATE INDEX IF NOT EXISTS idx_completed_orders_completed_at ON analytics."Completed_Orders" ("COMPLETED_AT" DESC);
CREATE INDEX IF NOT EXISTS idx_completed_orders_table_id     ON analytics."Completed_Orders" ("TABLE_ID");
CREATE INDEX IF NOT EXISTS idx_completed_orders_order_type   ON analytics."Completed_Orders" ("ORDER_TYPE");
CREATE INDEX IF NOT EXISTS idx_completed_orders_items_gin    ON analytics."Completed_Orders" USING gin ("ORDER_ITEMS");


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  10. GRANTS — Allow anon/authenticated DML on all domain tables        ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

GRANT ALL ON ALL TABLES IN SCHEMA menu       TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA orders     TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA tables     TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA staff      TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA tickets    TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA advance    TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA analytics  TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA events     TO anon, authenticated, service_role;

GRANT ALL ON ALL SEQUENCES IN SCHEMA menu       TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA orders     TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tables     TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA staff      TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tickets    TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA advance    TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA analytics  TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA events     TO anon, authenticated, service_role;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  11. ROW LEVEL SECURITY on actual tables                               ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- Helper: enable RLS + permissive ALL policy (matches existing project pattern)
DO $$
DECLARE
    t RECORD;
BEGIN
    FOR t IN
        SELECT schemaname, tablename
        FROM pg_tables
        WHERE schemaname IN ('menu','orders','tables','staff','tickets','advance','analytics','events')
    LOOP
        EXECUTE format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY', t.schemaname, t.tablename);
        EXECUTE format(
            'CREATE POLICY "Allow all" ON %I.%I FOR ALL USING (true) WITH CHECK (true)',
            t.schemaname, t.tablename
        );
    END LOOP;
END $$;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  12. PUBLIC VIEWS — Thin updatable proxies for Supabase JS client      ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
-- These let supabase.from('Table_Name') work unchanged.
-- security_invoker = on ensures RLS of underlying table applies.

CREATE OR REPLACE VIEW public."Restaurant_Tables"
    WITH (security_invoker = on) AS SELECT * FROM tables."Restaurant_Tables";

CREATE OR REPLACE VIEW public."Table_Reservations"
    WITH (security_invoker = on) AS SELECT * FROM tables."Table_Reservations";

CREATE OR REPLACE VIEW public."Table_Layout_Presets"
    WITH (security_invoker = on) AS SELECT * FROM tables."Table_Layout_Presets";

CREATE OR REPLACE VIEW public."Custom_Table_Templates"
    WITH (security_invoker = on) AS SELECT * FROM tables."Custom_Table_Templates";

CREATE OR REPLACE VIEW public."Menu_Categories"
    WITH (security_invoker = on) AS SELECT * FROM menu."Menu_Categories";

CREATE OR REPLACE VIEW public."Menu_Items"
    WITH (security_invoker = on) AS SELECT * FROM menu."Menu_Items";

CREATE OR REPLACE VIEW public."Menu_Item_Groups"
    WITH (security_invoker = on) AS SELECT * FROM menu."Menu_Item_Groups";

CREATE OR REPLACE VIEW public."Item_Groups"
    WITH (security_invoker = on) AS SELECT * FROM menu."Item_Groups";

CREATE OR REPLACE VIEW public."Restaurant_Orders"
    WITH (security_invoker = on) AS SELECT * FROM orders."Restaurant_Orders";

CREATE OR REPLACE VIEW public."Order_Items"
    WITH (security_invoker = on) AS SELECT * FROM orders."Order_Items";

CREATE OR REPLACE VIEW public."Discounts"
    WITH (security_invoker = on) AS SELECT * FROM orders."Discounts";

CREATE OR REPLACE VIEW public."Bill_Requests"
    WITH (security_invoker = on) AS SELECT * FROM orders."Bill_Requests";

CREATE OR REPLACE VIEW public."Order_Events"
    WITH (security_invoker = on) AS SELECT * FROM orders."Order_Events";

CREATE OR REPLACE VIEW public."Staff_Accounts"
    WITH (security_invoker = on) AS SELECT * FROM staff."Staff_Accounts";

CREATE OR REPLACE VIEW public."Staff_Codes"
    WITH (security_invoker = on) AS SELECT * FROM staff."Staff_Codes";

CREATE OR REPLACE VIEW public."Cashier_Staff"
    WITH (security_invoker = on) AS SELECT * FROM staff."Cashier_Staff";

CREATE OR REPLACE VIEW public."Dispatcher_Staff"
    WITH (security_invoker = on) AS SELECT * FROM staff."Dispatcher_Staff";

CREATE OR REPLACE VIEW public."Superviser_Staff"
    WITH (security_invoker = on) AS SELECT * FROM staff."Superviser_Staff";

CREATE OR REPLACE VIEW public."Ticket_Orders"
    WITH (security_invoker = on) AS SELECT * FROM tickets."Ticket_Orders";

CREATE OR REPLACE VIEW public."Ticket_Order_Items"
    WITH (security_invoker = on) AS SELECT * FROM tickets."Ticket_Order_Items";

CREATE OR REPLACE VIEW public."Ticket_Order_Group_Items"
    WITH (security_invoker = on) AS SELECT * FROM tickets."Ticket_Order_Group_Items";

CREATE OR REPLACE VIEW public."Advance_Orders"
    WITH (security_invoker = on) AS SELECT * FROM advance."Advance_Orders";

CREATE OR REPLACE VIEW public."Advance_Order_Items"
    WITH (security_invoker = on) AS SELECT * FROM advance."Advance_Order_Items";

CREATE OR REPLACE VIEW public."Completed_Orders"
    WITH (security_invoker = on) AS SELECT * FROM analytics."Completed_Orders";

CREATE OR REPLACE VIEW public."Restaurant_Events"
    WITH (security_invoker = on) AS SELECT * FROM events."Restaurant_Events";

-- Grant DML on all public views
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  13. SUPABASE REALTIME PUBLICATION (actual tables)                     ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'tables."Restaurant_Tables"',
        'tables."Table_Layout_Presets"',
        'tables."Custom_Table_Templates"',
        'menu."Menu_Items"',
        'menu."Menu_Categories"',
        'menu."Menu_Item_Groups"',
        'menu."Item_Groups"',
        'orders."Restaurant_Orders"',
        'orders."Order_Items"',
        'orders."Bill_Requests"',
        'orders."Order_Events"',
        'events."Restaurant_Events"',
        'advance."Advance_Orders"',
        'advance."Advance_Order_Items"',
        'analytics."Completed_Orders"',
        'tickets."Ticket_Orders"',
        'tickets."Ticket_Order_Items"',
        'tickets."Ticket_Order_Group_Items"'
    ]
    LOOP
        BEGIN
            EXECUTE format('ALTER TABLE %s REPLICA IDENTITY FULL', tbl);
        EXCEPTION WHEN OTHERS THEN
            NULL;
        END;
        BEGIN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %s', tbl);
        EXCEPTION WHEN OTHERS THEN
            NULL; -- already added
        END;
    END LOOP;
END $$;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  14. STORAGE BUCKET (menu-items images)                                ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'menu-items', 'menu-items', true, 5242880,
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO UPDATE SET
    public = true,
    file_size_limit = 5242880,
    allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif'];

DROP POLICY IF EXISTS "Public Access menu-items" ON storage.objects;
CREATE POLICY "Public Access menu-items"  ON storage.objects FOR SELECT USING (bucket_id = 'menu-items');
DROP POLICY IF EXISTS "Allow Upload menu-items" ON storage.objects;
CREATE POLICY "Allow Upload menu-items"   ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'menu-items');
DROP POLICY IF EXISTS "Allow Update menu-items" ON storage.objects;
CREATE POLICY "Allow Update menu-items"   ON storage.objects FOR UPDATE USING (bucket_id = 'menu-items');
DROP POLICY IF EXISTS "Allow Delete menu-items" ON storage.objects;
CREATE POLICY "Allow Delete menu-items"   ON storage.objects FOR DELETE USING (bucket_id = 'menu-items');


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  15. EXPOSE SCHEMAS TO PostgREST                                       ║
-- ╚══════════════════════════════════════════════════════════════════════════╝
-- This tells PostgREST to expose these schemas via the API.
-- The realtime subscriptions use the actual schema names.

ALTER ROLE authenticator SET pgrst.db_extra_search_path TO 'public, menu, orders, tables, staff, tickets, advance, analytics, events';
NOTIFY pgrst, 'reload config';


-- ============================================================================
-- Done!  Next steps:
--
--   1. Update .env with the new project's VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY
--   2. Run 002_seed_data.sql for sample data (update schema refs if needed)
--   3. Update realtime subscriptions in frontend to use domain schema names
--      e.g. schema: 'tables' for Restaurant_Tables, schema: 'orders' for
--      Restaurant_Orders, etc.
--   4. supabase.from('Table_Name') calls work unchanged via public views
-- ============================================================================
