-- ============================================================
-- Migration: Bill Requests + SERVED order status
-- Run in Supabase SQL Editor BEFORE deploying the customer interface
-- ============================================================

-- 1. Add SERVED status to Restaurant_Orders
ALTER TABLE public."Restaurant_Orders"
  DROP CONSTRAINT IF EXISTS restaurant_orders_order_status_check;

ALTER TABLE public."Restaurant_Orders"
  ADD CONSTRAINT restaurant_orders_order_status_check CHECK (
    "ORDER_STATUS" = ANY(ARRAY[
      'REQUESTED'::text,
      'VERIFIED'::text,
      'PREPARING'::text,
      'READY'::text,
      'SERVED'::text
    ])
  );

-- Fix missing schema requirements for mobile POS
ALTER TABLE public."Order_Items" ADD COLUMN IF NOT EXISTS "QUANTITY" integer DEFAULT 1;
ALTER TABLE public."Order_Items" ADD COLUMN IF NOT EXISTS "NOTES" text;
ALTER TABLE public."Menu_Items" ADD COLUMN IF NOT EXISTS "ITEM_IMAGE" text;


-- 2. Create Bill_Requests table
CREATE TABLE IF NOT EXISTS public."Bill_Requests" (
  "REQUEST_ID"     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "TABLE_ID"       bigint NOT NULL,
  "ORDER_ID"       bigint NULL,
  "PAYMENT_METHOD" text NOT NULL,
  "STATUS"         text NOT NULL DEFAULT 'REQUESTED',
  "REQUESTED_AT"   timestamp without time zone DEFAULT now(),
  CONSTRAINT "Bill_Requests_pkey" PRIMARY KEY ("REQUEST_ID"),
  CONSTRAINT "bill_requests_table_id_fkey" FOREIGN KEY ("TABLE_ID") REFERENCES public."Restaurant_Tables"("TABLE_ID") ON DELETE CASCADE,
  CONSTRAINT "bill_requests_order_id_fkey" FOREIGN KEY ("ORDER_ID") REFERENCES public."Restaurant_Orders"("ORDER_ID") ON DELETE SET NULL,
  CONSTRAINT "bill_requests_payment_check" CHECK (
    "PAYMENT_METHOD" = ANY(ARRAY['CASH'::text, 'CREDIT_CARD'::text, 'INSTAPAY_QR'::text])
  ),
  CONSTRAINT "bill_requests_status_check" CHECK (
    "STATUS" = ANY(ARRAY['REQUESTED'::text, 'PROCESSING'::text, 'PAID'::text, 'CANCELLED'::text])
  )
);

-- 3. Enable realtime for the tables (also enable via Dashboard → Database → Replication)
-- These lines ensure publication exists; run only once.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Menu_Items'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Menu_Items";
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Restaurant_Orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Restaurant_Orders";
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Order_Items'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Order_Items";
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Bill_Requests'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Bill_Requests";
  END IF;
END $$;

-- 4. RLS Policies — public customer access
-- (Skip if RLS is not yet enabled; enable per-table first if needed)

-- Menu_Items: public read
DROP POLICY IF EXISTS "Public can read menu items" ON public."Menu_Items";
CREATE POLICY "Public can read menu items"
  ON public."Menu_Items" FOR SELECT USING (true);

-- Menu_Categories: public read
DROP POLICY IF EXISTS "Public can read categories" ON public."Menu_Categories";
CREATE POLICY "Public can read categories"
  ON public."Menu_Categories" FOR SELECT USING (true);

-- Restaurant_Tables: public read
DROP POLICY IF EXISTS "Public can read tables" ON public."Restaurant_Tables";
CREATE POLICY "Public can read tables"
  ON public."Restaurant_Tables" FOR SELECT USING (true);

-- Restaurant_Orders: public insert + select
DROP POLICY IF EXISTS "Public can create orders" ON public."Restaurant_Orders";
CREATE POLICY "Public can create orders"
  ON public."Restaurant_Orders" FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read orders" ON public."Restaurant_Orders";
CREATE POLICY "Public can read orders"
  ON public."Restaurant_Orders" FOR SELECT USING (true);

-- Order_Items: public insert + select
DROP POLICY IF EXISTS "Public can create order items" ON public."Order_Items";
CREATE POLICY "Public can create order items"
  ON public."Order_Items" FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read order items" ON public."Order_Items";
CREATE POLICY "Public can read order items"
  ON public."Order_Items" FOR SELECT USING (true);

-- Bill_Requests: public insert + select
DROP POLICY IF EXISTS "Public can create bill requests" ON public."Bill_Requests";
CREATE POLICY "Public can create bill requests"
  ON public."Bill_Requests" FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read bill requests" ON public."Bill_Requests";
CREATE POLICY "Public can read bill requests"
  ON public."Bill_Requests" FOR SELECT USING (true);
