-- ==============================================================================
-- Migration 010: Order Logs & Historical Event Tracking
--
-- 1. Adds PAYMENT_METHOD to Restaurant_Orders (defaults to 'CASH').
-- 2. Creates Order_Events table for immutable lifecycle event logging.
-- 3. Adds performance indexes on Restaurant_Orders and Order_Events.
-- 4. Sets up Supabase realtime publication and RLS policies.
-- ==============================================================================

-- Step 1: Add PAYMENT_METHOD to Restaurant_Orders if not exists
ALTER TABLE public."Restaurant_Orders"
ADD COLUMN IF NOT EXISTS "PAYMENT_METHOD" text NULL DEFAULT 'CASH';

-- Update existing completed orders to have PAYMENT_METHOD = 'CASH' if null
UPDATE public."Restaurant_Orders"
SET "PAYMENT_METHOD" = 'CASH'
WHERE "ORDER_STATUS" = 'COMPLETED' AND "PAYMENT_METHOD" IS NULL;

-- Step 2: Create Order_Events table
CREATE TABLE IF NOT EXISTS public."Order_Events" (
  "EVENT_ID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ORDER_ID" bigint NOT NULL,
  "EVENT_TYPE" text NOT NULL,
  "PREVIOUS_STATUS" text NULL,
  "NEW_STATUS" text NOT NULL,
  "TIMESTAMP" timestamp without time zone DEFAULT now(),
  "ACTOR" text NULL,
  "REASON" text NULL,
  "METADATA" jsonb NULL,
  CONSTRAINT "Order_Events_pkey" PRIMARY KEY ("EVENT_ID"),
  CONSTRAINT "order_events_order_id_fkey" FOREIGN KEY ("ORDER_ID")
    REFERENCES public."Restaurant_Orders"("ORDER_ID") ON DELETE CASCADE
);

-- Step 3: Performance Indexes
CREATE INDEX IF NOT EXISTS idx_restaurant_orders_time
  ON public."Restaurant_Orders" ("TIME" DESC);

CREATE INDEX IF NOT EXISTS idx_restaurant_orders_status
  ON public."Restaurant_Orders" ("ORDER_STATUS");

CREATE INDEX IF NOT EXISTS idx_restaurant_orders_table_id
  ON public."Restaurant_Orders" ("TABLE_ID");

CREATE INDEX IF NOT EXISTS idx_order_events_order_id
  ON public."Order_Events" ("ORDER_ID", "TIMESTAMP" ASC);

-- Step 4: Realtime Publication
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Order_Events'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Order_Events";
  END IF;
END $$;

-- Step 5: Row Level Security Policies
ALTER TABLE public."Order_Events" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read order events" ON public."Order_Events";
CREATE POLICY "Public can read order events"
  ON public."Order_Events" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can insert order events" ON public."Order_Events";
CREATE POLICY "Public can insert order events"
  ON public."Order_Events" FOR INSERT WITH CHECK (true);
