-- Migration 011: Staff Accounts and Role-Based Access Control
-- Description: Creates the Staff_Accounts table to store staff user profiles,
-- roles, permissions, contact details, and account statuses.

CREATE TABLE IF NOT EXISTS public."Staff_Accounts" (
  "ACCOUNT_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AUTH_USER_ID" UUID NULL,
  "FULL_NAME" TEXT NOT NULL,
  "EMAIL" TEXT NOT NULL UNIQUE,
  "ROLE" TEXT NOT NULL DEFAULT 'STAFF',
  "STATUS" TEXT NOT NULL DEFAULT 'ACTIVE',
  "PERMISSIONS" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "PHONE" TEXT NULL,
  "NOTES" TEXT NULL,
  "CREATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "UPDATED_AT" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "LAST_LOGIN" TIMESTAMP WITH TIME ZONE NULL,

  CONSTRAINT staff_accounts_role_check CHECK (
    "ROLE" = ANY (ARRAY['ADMIN'::TEXT, 'MANAGER'::TEXT, 'CASHIER'::TEXT, 'KITCHEN'::TEXT, 'STAFF'::TEXT])
  ),
  CONSTRAINT staff_accounts_status_check CHECK (
    "STATUS" = ANY (ARRAY['ACTIVE'::TEXT, 'INACTIVE'::TEXT, 'SUSPENDED'::TEXT])
  )
) TABLESPACE pg_default;

-- Create indexes for frequent lookups
CREATE INDEX IF NOT EXISTS idx_staff_accounts_email ON public."Staff_Accounts" ("EMAIL");
CREATE INDEX IF NOT EXISTS idx_staff_accounts_role ON public."Staff_Accounts" ("ROLE");
CREATE INDEX IF NOT EXISTS idx_staff_accounts_status ON public."Staff_Accounts" ("STATUS");

-- Enable Row Level Security (RLS)
ALTER TABLE public."Staff_Accounts" ENABLE ROW LEVEL SECURITY;

-- Allow read access for authenticated staff and anon clients for POS operations
CREATE POLICY "Allow public read access to Staff_Accounts"
  ON public."Staff_Accounts"
  FOR SELECT
  USING (true);

CREATE POLICY "Allow insert to Staff_Accounts"
  ON public."Staff_Accounts"
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow update to Staff_Accounts"
  ON public."Staff_Accounts"
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow delete to Staff_Accounts"
  ON public."Staff_Accounts"
  FOR DELETE
  USING (true);

-- Seed primary Administrator account and sample restaurant staff
INSERT INTO public."Staff_Accounts" (
  "FULL_NAME",
  "EMAIL",
  "ROLE",
  "STATUS",
  "PERMISSIONS",
  "PHONE",
  "NOTES"
)
VALUES
  (
    'Vincent Administrator',
    'taponakawnt123@gmail.com',
    'ADMIN',
    'ACTIVE',
    ARRAY['manage_accounts', 'manage_menu', 'manage_tables', 'access_kitchen', 'access_cashier', 'access_analytics', 'view_order_logs']::TEXT[],
    '+63 917 123 4567',
    'Primary store administrator and owner account.'
  ),
  (
    'Maria Santos',
    'manager.maria@monolithpos.com',
    'MANAGER',
    'ACTIVE',
    ARRAY['manage_menu', 'manage_tables', 'access_kitchen', 'access_cashier', 'access_analytics', 'view_order_logs']::TEXT[],
    '+63 918 234 5678',
    'Shift manager and restaurant operations supervisor.'
  ),
  (
    'Juan Dela Cruz',
    'cashier.juan@monolithpos.com',
    'CASHIER',
    'ACTIVE',
    ARRAY['access_cashier', 'manage_tables', 'view_order_logs']::TEXT[],
    '+63 919 345 6789',
    'Lead cashier for front counter and bill-out checkout.'
  ),
  (
    'Chef Roberto Gonzales',
    'kitchen.roberto@monolithpos.com',
    'KITCHEN',
    'ACTIVE',
    ARRAY['access_kitchen', 'manage_menu']::TEXT[],
    '+63 920 456 7890',
    'Head chef managing cooking queue and ingredient inventory.'
  ),
  (
    'Elena Reyes',
    'staff.elena@monolithpos.com',
    'STAFF',
    'ACTIVE',
    ARRAY['manage_tables', 'access_kitchen']::TEXT[],
    '+63 921 567 8901',
    'Floor attendant and table server.'
  )
ON CONFLICT ("EMAIL") DO UPDATE SET
  "FULL_NAME" = EXCLUDED."FULL_NAME",
  "ROLE" = EXCLUDED."ROLE",
  "STATUS" = EXCLUDED."STATUS",
  "PERMISSIONS" = EXCLUDED."PERMISSIONS",
  "PHONE" = EXCLUDED."PHONE",
  "NOTES" = EXCLUDED."NOTES",
  "UPDATED_AT" = NOW();
