-- Migration 013: Restaurant Events
-- Description: Creates the Restaurant_Events table for managing scheduled events.
-- Status (Scheduled/Ongoing/Completed) is derived at application layer from timestamps
-- Only IS_CANCELLED is persisted for user-set cancellations

CREATE TABLE IF NOT EXISTS public."Restaurant_Events" (
  "EVENT_ID"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TITLE"               TEXT NOT NULL,
  "DESCRIPTION"         TEXT NULL,
  "CATEGORY"            TEXT NOT NULL DEFAULT 'Other',
  "COLOR"               TEXT NULL,
  "START_AT"            TIMESTAMP WITH TIME ZONE NOT NULL,
  "END_AT"              TIMESTAMP WITH TIME ZONE NOT NULL,
  "LOCATION"            TEXT NULL,
  "ORGANIZER"           TEXT NULL,
  "EXPECTED_ATTENDEES"  INTEGER NULL CHECK ("EXPECTED_ATTENDEES" IS NULL OR "EXPECTED_ATTENDEES" >= 0),
  "CONTACT_NAME"        TEXT NULL,
  "CONTACT_PHONE"       TEXT NULL,
  "CONTACT_EMAIL"       TEXT NULL,
  "NOTES"               TEXT NULL,
  "IS_CANCELLED"        BOOLEAN NOT NULL DEFAULT FALSE,
  "CREATED_BY"          TEXT NULL,
  "CREATED_AT"          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "UPDATED_AT"          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "UPDATED_BY"          TEXT NULL,
  "DELETED_AT"          TIMESTAMP WITH TIME ZONE NULL,

  CONSTRAINT events_end_after_start CHECK ("END_AT" >= "START_AT"),
  CONSTRAINT events_category_check CHECK (
    "CATEGORY" = ANY (ARRAY[
      'Private Event', 'Birthday', 'Corporate Event', 'Meeting',
      'Reservation', 'Catering', 'Promotion', 'Holiday', 'Other'
    ]::TEXT[])
  )
) TABLESPACE pg_default;

-- Indexes for efficient calendar range queries
CREATE INDEX IF NOT EXISTS idx_events_start_at  ON public."Restaurant_Events" ("START_AT");
CREATE INDEX IF NOT EXISTS idx_events_end_at    ON public."Restaurant_Events" ("END_AT");
CREATE INDEX IF NOT EXISTS idx_events_deleted   ON public."Restaurant_Events" ("DELETED_AT");
CREATE INDEX IF NOT EXISTS idx_events_cancelled ON public."Restaurant_Events" ("IS_CANCELLED");

-- Enable Row Level Security (RLS) — follows same pattern as Staff_Accounts
ALTER TABLE public."Restaurant_Events" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to Restaurant_Events"
  ON public."Restaurant_Events"
  FOR SELECT
  USING (true);

CREATE POLICY "Allow insert to Restaurant_Events"
  ON public."Restaurant_Events"
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow update to Restaurant_Events"
  ON public."Restaurant_Events"
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow delete from Restaurant_Events"
  ON public."Restaurant_Events"
  FOR DELETE
  USING (true);

-- Enable Realtime for live updates across connected clients
ALTER PUBLICATION supabase_realtime ADD TABLE public."Restaurant_Events";
