-- ============================================================
-- Migration 014: Advance Orders
-- Description: Creates Advance_Orders and Advance_Order_Items tables
-- for pre-ordering before arrival with a 30-minute expiration countdown.
-- These tables are completely isolated from normal table/customer orders.
-- ============================================================

-- 1. Create Advance_Orders table
CREATE TABLE IF NOT EXISTS public."Advance_Orders" (
  "ADVANCE_ORDER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ORDER_NUMBER"     TEXT NOT NULL UNIQUE,
  "SESSION_TOKEN"    TEXT NOT NULL UNIQUE,
  "CUSTOMER_NAME"    TEXT NOT NULL,
  "DINING_TYPE"      TEXT NOT NULL DEFAULT 'dine-in',
  "STATUS"           TEXT NOT NULL DEFAULT 'PENDING',
  "SUBTOTAL"         NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  "TOTAL_AMOUNT"     NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  "NOTES"            TEXT NULL,
  "CREATED_AT"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "EXPIRES_AT"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (NOW() + INTERVAL '30 minutes'),
  "CONFIRMED_AT"     TIMESTAMP WITH TIME ZONE NULL,
  "COMPLETED_AT"     TIMESTAMP WITH TIME ZONE NULL,
  "CANCELLED_AT"     TIMESTAMP WITH TIME ZONE NULL,

  CONSTRAINT advance_orders_dining_type_check CHECK (
    "DINING_TYPE" = ANY (ARRAY['dine-in'::TEXT, 'take-away'::TEXT])
  ),
  CONSTRAINT advance_orders_status_check CHECK (
    "STATUS" = ANY (ARRAY[
      'PENDING'::TEXT,
      'CONFIRMED'::TEXT,
      'PREPARING'::TEXT,
      'READY'::TEXT,
      'COMPLETED'::TEXT,
      'CANCELLED'::TEXT,
      'EXPIRED'::TEXT
    ])
  )
) TABLESPACE pg_default;

-- 2. Create Advance_Order_Items table
CREATE TABLE IF NOT EXISTS public."Advance_Order_Items" (
  "ADVANCE_ITEM_ID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ADVANCE_ORDER_ID" BIGINT NOT NULL REFERENCES public."Advance_Orders"("ADVANCE_ORDER_ID") ON DELETE CASCADE,
  "ITEM_ID"          BIGINT NOT NULL REFERENCES public."Menu_Items"("ITEM_ID"),
  "ITEM_NAME"        TEXT NOT NULL,
  "QUANTITY"         INTEGER NOT NULL DEFAULT 1 CHECK ("QUANTITY" > 0),
  "UNIT_PRICE"       NUMERIC(10, 2) NOT NULL,
  "TOTAL_PRICE"      NUMERIC(10, 2) NOT NULL,
  "NOTES"            TEXT NULL,
  "CREATED_AT"       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
) TABLESPACE pg_default;

-- 3. Indexes for fast token lookup and lifecycle queries
CREATE INDEX IF NOT EXISTS idx_advance_orders_session_token ON public."Advance_Orders" ("SESSION_TOKEN");
CREATE INDEX IF NOT EXISTS idx_advance_orders_order_number  ON public."Advance_Orders" ("ORDER_NUMBER");
CREATE INDEX IF NOT EXISTS idx_advance_orders_status        ON public."Advance_Orders" ("STATUS");
CREATE INDEX IF NOT EXISTS idx_advance_orders_expires_at    ON public."Advance_Orders" ("EXPIRES_AT");
CREATE INDEX IF NOT EXISTS idx_advance_order_items_order_id ON public."Advance_Order_Items" ("ADVANCE_ORDER_ID");
CREATE INDEX IF NOT EXISTS idx_advance_order_items_item_id  ON public."Advance_Order_Items" ("ITEM_ID");

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public."Advance_Orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Advance_Order_Items" ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for Advance_Orders
DROP POLICY IF EXISTS "Public can create advance orders" ON public."Advance_Orders";
CREATE POLICY "Public can create advance orders"
  ON public."Advance_Orders"
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read advance orders" ON public."Advance_Orders";
CREATE POLICY "Public can read advance orders"
  ON public."Advance_Orders"
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Public can update advance orders" ON public."Advance_Orders";
CREATE POLICY "Public can update advance orders"
  ON public."Advance_Orders"
  FOR UPDATE
  USING (true);

-- 6. RLS Policies for Advance_Order_Items
DROP POLICY IF EXISTS "Public can create advance order items" ON public."Advance_Order_Items";
CREATE POLICY "Public can create advance order items"
  ON public."Advance_Order_Items"
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read advance order items" ON public."Advance_Order_Items";
CREATE POLICY "Public can read advance order items"
  ON public."Advance_Order_Items"
  FOR SELECT
  USING (true);

-- 7. Add to Realtime Publication if available
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Advance_Orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Advance_Orders";
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND tablename = 'Advance_Order_Items'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public."Advance_Order_Items";
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    -- Silently handle if publication does not exist in local env
    NULL;
END $$;
