-- ==============================================================================
-- Migration 020: Populate Database with Realistic Completed Orders for Analytics
--
-- Features:
--   1. Populates the dedicated public."Completed_Orders" table for historical logging & analytics.
--   2. Dynamically reads available Menu_Items, Menu_Categories, and Restaurant_Tables.
--   3. Inserts ONLY COMPLETED orders (ORDER_STATUS = 'COMPLETED') with both DINE-IN and TAKEOUT types.
--   4. Date spread across the last 75 days to support all analytics presets:
--      Today, Yesterday, Last 7 Days, Last 30 Days, This Month, Last Month, and custom ranges.
--   5. Realistic operating hours (10:00 - 22:00) with authentic lunch (11:30-13:30) and dinner (17:30-20:30) rushes.
--   6. Full analytics KPI compatibility:
--      - GUEST_COUNT (party sizes 1-6 for dine-in, 1-2 for takeout)
--      - ITEM_COUNT (total units ordered in each order)
--      - ORDER_ITEMS JSONB snapshot (item_id, item_name, category_id, category_name, price, quantity)
--      - Accurate kitchen timestamps (READY_AT, SERVED_AT, COMPLETED_AT) for prep & serving time KPIs
--      - Exact SUBTOTAL_BILL and TOTAL_BILL matching items in ORDER_ITEMS
--      - Realistic discount sampling (~15% Senior/PWD 20% discount)
--      - Channel breakdown (Cashier vs Customer App)
--      - Payment method distribution (CASH, CREDIT_CARD, INSTAPAY_QR)
--
-- Instructions:
--   Open Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- Step 1: Ensure Completed_Orders table exists
CREATE TABLE IF NOT EXISTS public."Completed_Orders" (
    "ORDER_ID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ORIGINAL_ORDER_ID" bigint NULL,
    "TABLE_ID" bigint NULL,
    "TABLE_NUM" int NULL,
    "ORDER_TYPE" text NOT NULL DEFAULT 'DINE-IN',
    "REQUESTED_FROM" text NOT NULL DEFAULT 'Cashier',
    "ORDER_STATUS" text NOT NULL DEFAULT 'COMPLETED',
    "GUEST_COUNT" int NOT NULL DEFAULT 1,
    "ITEM_COUNT" int NOT NULL DEFAULT 0,
    "SUBTOTAL_BILL" double precision NOT NULL DEFAULT 0,
    "TOTAL_BILL" double precision NOT NULL DEFAULT 0,
    "DISCOUNT_AMOUNT" double precision NOT NULL DEFAULT 0,
    "PAYMENT_METHOD" text NOT NULL DEFAULT 'CASH',
    "TIME" timestamp without time zone NOT NULL DEFAULT now(),
    "READY_AT" timestamp without time zone NULL,
    "SERVED_AT" timestamp without time zone NULL,
    "COMPLETED_AT" timestamp without time zone NULL,
    "KITCHEN_NOTE" text NULL,
    "SERVER_NOTE" text NULL,
    "ORDER_ITEMS" jsonb NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT "Completed_Orders_pkey" PRIMARY KEY ("ORDER_ID")
);

-- Step 2: Seed Generation Script
DO $$
DECLARE
    -- Configuration parameters
    v_total_orders_to_create int := 500; -- Total orders to generate
    v_days_back int := 75;               -- Timespan window in days

    -- Dynamic table and menu item storage
    v_table_ids bigint[];
    v_table_nums int[];
    v_item_ids bigint[];
    v_item_prices double precision[];
    v_item_names text[];
    v_category_ids bigint[];
    v_category_names text[];
    v_num_tables int;
    v_num_items int;

    -- Order level variables
    v_table_id bigint;
    v_table_num int;
    v_order_type text;
    v_requested_from text;
    v_payment_method text;
    v_guest_count int;
    v_kitchen_note text;
    v_server_note text;

    -- Date & timestamp calculation variables
    v_random_days double precision;
    v_random_hour int;
    v_random_minute int;
    v_random_second int;
    v_order_time timestamp without time zone;
    v_prep_minutes int;
    v_delivery_minutes int;
    v_turnaround_minutes int;
    v_ready_at timestamp without time zone;
    v_served_at timestamp without time zone;
    v_completed_at timestamp without time zone;

    -- Order items generation variables
    v_num_distinct_items int;
    v_chosen_item_indices int[];
    v_item_idx int;
    v_item_id bigint;
    v_item_qty int;
    v_total_item_count int;
    v_subtotal double precision;
    v_total double precision;
    v_discount_amount double precision;
    v_is_discounted boolean;
    v_order_items jsonb;

    -- Loop indices & helpers
    i int;
    j int;
    k int;
    v_try int;
    v_already_chosen boolean;
    v_table_pick_idx int;

    -- Notes & payment method lookup pools
    v_k_notes text[] := ARRAY[
        'Extra crispy please',
        'Less oil',
        'No onions if possible',
        'Well done egg',
        'Pack sauce on the side',
        'Separate chili sauce',
        'Rice well heated',
        'Less ice for beverages'
    ];
    v_s_notes text[] := ARRAY[
        'Customer asked for extra napkins',
        'Regular dining customer',
        'Table requested water immediately',
        'Split bill requested earlier',
        'Served with priority'
    ];
    v_payment_methods text[] := ARRAY['CASH', 'CREDIT_CARD', 'INSTAPAY_QR'];

BEGIN
    -- 1. Fetch available tables from Restaurant_Tables
    SELECT 
        array_agg("TABLE_ID"),
        array_agg(COALESCE("TABLE_NUM", "TABLE_ID")::int)
    INTO v_table_ids, v_table_nums 
    FROM public."Restaurant_Tables";

    -- 2. Fetch available menu items joined with categories
    SELECT 
        array_agg(m."ITEM_ID"),
        array_agg(COALESCE(m."ITEM_PRICE", 0)::double precision),
        array_agg(COALESCE(m."ITEM_NAME", 'Dish')),
        array_agg(COALESCE(m."CATEGORY_ID", 0)::bigint),
        array_agg(COALESCE(c."CATEGORY_NAME", 'Uncategorized'))
    INTO v_item_ids, v_item_prices, v_item_names, v_category_ids, v_category_names
    FROM public."Menu_Items" m
    LEFT JOIN public."Menu_Categories" c ON m."CATEGORY_ID" = c."CATEGORY_ID"
    WHERE m."ITEM_STATUS" = 'AVAILABLE' OR m."ITEM_STATUS" IS NULL;

    v_num_tables := COALESCE(array_length(v_table_ids, 1), 0);
    v_num_items := COALESCE(array_length(v_item_ids, 1), 0);

    IF v_num_tables = 0 THEN
        RAISE EXCEPTION 'No tables found in Restaurant_Tables. Please seed tables first.';
    END IF;

    IF v_num_items = 0 THEN
        RAISE EXCEPTION 'No menu items found in Menu_Items. Please seed menu items first.';
    END IF;

    RAISE NOTICE 'Starting generation of % completed orders in Completed_Orders across the last % days...', v_total_orders_to_create, v_days_back;
    RAISE NOTICE 'Found % tables and % menu items in database.', v_num_tables, v_num_items;

    FOR i IN 1..v_total_orders_to_create LOOP

        -- A. Determine Order Type (70% DINE-IN, 30% TAKEOUT)
        v_table_pick_idx := 1 + floor(random() * v_num_tables)::int;
        v_table_id := v_table_ids[v_table_pick_idx];
        v_table_num := v_table_nums[v_table_pick_idx];

        IF random() < 0.70 THEN
            v_order_type := 'DINE-IN';
            -- Party sizes: 1-2 guests (45%), 3-4 guests (35%), 5-6 guests (20%)
            IF random() < 0.45 THEN
                v_guest_count := 1 + floor(random() * 2)::int;
            ELSIF random() < 0.80 THEN
                v_guest_count := 3 + floor(random() * 2)::int;
            ELSE
                v_guest_count := 5 + floor(random() * 2)::int;
            END IF;
        ELSE
            v_order_type := 'TAKEOUT';
            v_guest_count := 1 + floor(random() * 2)::int;
        END IF;

        -- B. Channel Breakdown (60% Cashier, 40% Customer App)
        IF random() < 0.60 THEN
            v_requested_from := 'Cashier';
        ELSE
            v_requested_from := 'Customer';
        END IF;

        -- C. Payment Method (50% CASH, 30% CREDIT_CARD, 20% INSTAPAY_QR)
        IF random() < 0.50 THEN
            v_payment_method := 'CASH';
        ELSIF random() < 0.80 THEN
            v_payment_method := 'CREDIT_CARD';
        ELSE
            v_payment_method := 'INSTAPAY_QR';
        END IF;

        -- D. Timestamp Generation (Operating hours: 10:00 - 22:00 with peak rushes)
        v_random_days := random() * v_days_back;
        
        -- Hour distribution:
        -- 45% Dinner rush (17:00 - 20:59)
        -- 35% Lunch rush (11:00 - 13:59)
        -- 20% Off-peak (10:00 - 10:59 or 14:00 - 16:59 or 21:00 - 21:59)
        IF random() < 0.45 THEN
            v_random_hour := 17 + floor(random() * 4)::int;
        ELSIF random() < 0.80 THEN
            v_random_hour := 11 + floor(random() * 3)::int;
        ELSE
            IF random() < 0.60 THEN
                v_random_hour := 14 + floor(random() * 3)::int;
            ELSIF random() < 0.85 THEN
                v_random_hour := 10;
            ELSE
                v_random_hour := 21;
            END IF;
        END IF;

        v_random_minute := floor(random() * 60)::int;
        v_random_second := floor(random() * 60)::int;

        v_order_time := date_trunc('second', CURRENT_TIMESTAMP - (v_random_days || ' days')::interval);
        v_order_time := date_trunc('day', v_order_time) 
                        + (v_random_hour || ' hours')::interval 
                        + (v_random_minute || ' minutes')::interval 
                        + (v_random_second || ' seconds')::interval;

        -- Prevent timestamps from being in the future or within the last 30 minutes
        IF v_order_time > CURRENT_TIMESTAMP - INTERVAL '30 minutes' THEN
            v_order_time := CURRENT_TIMESTAMP - (INTERVAL '1 hour' + (random() * INTERVAL '4 hours'));
        END IF;

        -- E. Kitchen & Serving Durations
        -- Prep duration: 8 to 22 minutes
        v_prep_minutes := 8 + floor(random() * 15)::int;
        -- Delivery duration: 2 to 6 minutes
        v_delivery_minutes := 2 + floor(random() * 5)::int;
        
        v_ready_at := v_order_time + (v_prep_minutes || ' minutes')::interval;
        v_served_at := v_ready_at + (v_delivery_minutes || ' minutes')::interval;

        -- Turnaround duration (Dine-in diners stay 20-55 mins, Takeout leaves in 2-6 mins)
        IF v_order_type = 'TAKEOUT' THEN
            v_turnaround_minutes := 2 + floor(random() * 5)::int;
        ELSE
            v_turnaround_minutes := 20 + floor(random() * 35)::int;
        END IF;

        v_completed_at := v_served_at + (v_turnaround_minutes || ' minutes')::interval;

        -- F. Occasional Notes
        IF random() < 0.20 THEN
            v_kitchen_note := v_k_notes[1 + floor(random() * array_length(v_k_notes, 1))::int];
        ELSE
            v_kitchen_note := NULL;
        END IF;

        IF random() < 0.15 THEN
            v_server_note := v_s_notes[1 + floor(random() * array_length(v_s_notes, 1))::int];
        ELSE
            v_server_note := NULL;
        END IF;

        -- G. Select 1 to 4 distinct items from the menu
        v_num_distinct_items := 1 + floor(random() * LEAST(4, v_num_items))::int;
        v_chosen_item_indices := '{}';
        
        FOR j IN 1..v_num_distinct_items LOOP
            v_try := 1 + floor(random() * v_num_items)::int;
            v_already_chosen := false;
            FOREACH k IN ARRAY v_chosen_item_indices LOOP
                IF k = v_try THEN
                    v_already_chosen := true;
                END IF;
            END LOOP;
            IF NOT v_already_chosen THEN
                v_chosen_item_indices := array_append(v_chosen_item_indices, v_try);
            END IF;
        END LOOP;

        IF array_length(v_chosen_item_indices, 1) IS NULL OR array_length(v_chosen_item_indices, 1) = 0 THEN
            v_chosen_item_indices := ARRAY[1 + floor(random() * v_num_items)::int];
        END IF;

        -- Build rich ORDER_ITEMS JSONB and compute subtotal
        v_subtotal := 0;
        v_total_item_count := 0;
        v_order_items := '[]'::jsonb;

        FOREACH v_item_idx IN ARRAY v_chosen_item_indices LOOP
            -- Portion quantity per distinct item (1 to 2 portions)
            v_item_qty := 1 + floor(random() * 2)::int;
            v_subtotal := v_subtotal + (v_item_prices[v_item_idx] * v_item_qty);
            v_total_item_count := v_total_item_count + v_item_qty;

            v_order_items := v_order_items || jsonb_build_object(
                'item_id', v_item_ids[v_item_idx],
                'item_name', v_item_names[v_item_idx],
                'category_id', v_category_ids[v_item_idx],
                'category_name', v_category_names[v_item_idx],
                'price', v_item_prices[v_item_idx],
                'quantity', v_item_qty
            );
        END LOOP;

        -- Apply ~15% chance of Senior / PWD 20% discount
        v_is_discounted := (random() < 0.15);
        IF v_is_discounted THEN
            v_total := ROUND((v_subtotal * 0.8)::numeric, 2);
            v_discount_amount := ROUND((v_subtotal * 0.2)::numeric, 2);
        ELSE
            v_total := v_subtotal;
            v_discount_amount := 0;
        END IF;

        -- H. Insert into Completed_Orders
        INSERT INTO public."Completed_Orders" (
            "TABLE_ID",
            "TABLE_NUM",
            "REQUESTED_FROM",
            "ORDER_TYPE",
            "ORDER_STATUS",
            "SUBTOTAL_BILL",
            "TOTAL_BILL",
            "DISCOUNT_AMOUNT",
            "TIME",
            "KITCHEN_NOTE",
            "SERVER_NOTE",
            "GUEST_COUNT",
            "ITEM_COUNT",
            "READY_AT",
            "SERVED_AT",
            "COMPLETED_AT",
            "PAYMENT_METHOD",
            "ORDER_ITEMS"
        ) VALUES (
            v_table_id,
            v_table_num,
            v_requested_from,
            v_order_type,
            'COMPLETED',
            v_subtotal,
            v_total,
            v_discount_amount,
            v_order_time,
            v_kitchen_note,
            v_server_note,
            v_guest_count,
            v_total_item_count,
            v_ready_at,
            v_served_at,
            v_completed_at,
            v_payment_method,
            v_order_items
        );

    END LOOP;

    RAISE NOTICE 'Generation complete! Successfully inserted % completed orders into Completed_Orders.', v_total_orders_to_create;
END $$;

-- Verification Queries
SELECT 
    "ORDER_STATUS",
    "ORDER_TYPE",
    COUNT(*) AS total_orders,
    SUM("GUEST_COUNT") AS total_guests_pax,
    SUM("ITEM_COUNT") AS total_items_ordered,
    ROUND(SUM("TOTAL_BILL")::numeric, 2) AS total_revenue,
    ROUND(AVG("TOTAL_BILL")::numeric, 2) AS average_order_value,
    MIN("TIME") AS oldest_order,
    MAX("TIME") AS newest_order
FROM public."Completed_Orders"
WHERE "ORDER_STATUS" = 'COMPLETED'
GROUP BY "ORDER_STATUS", "ORDER_TYPE";
