-- ==============================================================================
-- Migration 021: Create Dedicated Completed Orders Log Table (Completed_Orders)
-- Schema: system_history."Completed_Orders" + public."Completed_Orders" View
--
-- Purpose:
--   Permanently archives all completed, billed-out dining and ticket orders
--   in system_history schema so they are never deleted upon table settlement.
--   Stores complete order metadata (seated pax / GUEST_COUNT, bills, discounts,
--   kitchen/serving timestamps, notes) along with a rich JSONB snapshot of all
--   ordered items (item_id, item_name, category_id, category_name, price, quantity).
--
-- Instructions:
--   Open Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- Step 0: Ensure schema exists and permissions granted
CREATE SCHEMA IF NOT EXISTS system_history;
GRANT USAGE ON SCHEMA system_history TO anon, authenticated, service_role;

-- Step 1: Create Completed_Orders table in system_history schema
CREATE TABLE IF NOT EXISTS system_history."Completed_Orders" (
    "ORDER_ID" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ORIGINAL_ORDER_ID" bigint NULL,
    "TABLE_ID" bigint NULL,
    "TABLE_NUM" int NULL,
    "ORDER_TYPE" text NOT NULL DEFAULT 'DINE-IN',
    "REQUESTED_FROM" text NOT NULL DEFAULT 'Cashier',
    "ORDER_STATUS" text NOT NULL DEFAULT 'COMPLETED',
    "GUEST_COUNT" int NOT NULL DEFAULT 1,
    "ITEM_COUNT" int NOT NULL DEFAULT 0,
    "SUBTOTAL_BILL" double precision NOT NULL DEFAULT 0,
    "TOTAL_BILL" double precision NOT NULL DEFAULT 0,
    "DISCOUNT_AMOUNT" double precision NOT NULL DEFAULT 0,
    "PAYMENT_METHOD" text NOT NULL DEFAULT 'CASH',
    "TIME" timestamp without time zone NOT NULL DEFAULT now(),
    "READY_AT" timestamp without time zone NULL,
    "SERVED_AT" timestamp without time zone NULL,
    "COMPLETED_AT" timestamp without time zone NULL,
    "KITCHEN_NOTE" text NULL,
    "SERVER_NOTE" text NULL,
    "ORDER_ITEMS" jsonb NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT "Completed_Orders_pkey" PRIMARY KEY ("ORDER_ID")
);

-- Step 2: Performance Indexes
CREATE INDEX IF NOT EXISTS idx_completed_orders_time
    ON system_history."Completed_Orders" ("TIME" DESC);

CREATE INDEX IF NOT EXISTS idx_completed_orders_completed_at
    ON system_history."Completed_Orders" ("COMPLETED_AT" DESC);

CREATE INDEX IF NOT EXISTS idx_completed_orders_table_id
    ON system_history."Completed_Orders" ("TABLE_ID");

CREATE INDEX IF NOT EXISTS idx_completed_orders_order_type
    ON system_history."Completed_Orders" ("ORDER_TYPE");

CREATE INDEX IF NOT EXISTS idx_completed_orders_items_gin
    ON system_history."Completed_Orders" USING gin ("ORDER_ITEMS");

-- Step 3: Grants & Permissions
GRANT ALL ON TABLE system_history."Completed_Orders" TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA system_history TO anon, authenticated, service_role;

-- Step 4: Realtime Publication
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'system_history'
          AND tablename = 'Completed_Orders'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE system_history."Completed_Orders";
    END IF;
END $$;

-- Step 5: Row Level Security Policies
ALTER TABLE system_history."Completed_Orders" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read completed orders" ON system_history."Completed_Orders";
CREATE POLICY "Public can read completed orders"
    ON system_history."Completed_Orders" FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can insert completed orders" ON system_history."Completed_Orders";
CREATE POLICY "Public can insert completed orders"
    ON system_history."Completed_Orders" FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can update completed orders" ON system_history."Completed_Orders";
CREATE POLICY "Public can update completed orders"
    ON system_history."Completed_Orders" FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public can delete completed orders" ON system_history."Completed_Orders";
CREATE POLICY "Public can delete completed orders"
    ON system_history."Completed_Orders" FOR DELETE USING (true);

-- Step 6: Public View (with security_invoker = on) for PostgREST Access
CREATE OR REPLACE VIEW public."Completed_Orders"
    WITH (security_invoker = on) AS
    SELECT * FROM system_history."Completed_Orders";

GRANT ALL ON public."Completed_Orders" TO anon, authenticated, service_role;
