-- ==============================================================================
-- Migration 022: Create Dedicated Action History & Audit Log Table
-- Schema: system_history."Action_History" + public."Action_History" View
--
-- Purpose:
--   Stores a complete audit trail of actions performed within the POS system.
--   Tracks what action was done, which module it belongs to, what entity was affected,
--   and exactly who did it (identified by STAFF_CODE from Staff_Codes, along with a
--   snapshot of STAFF_NAME and STAFF_ROLE for long-term historical integrity).
--
-- Instructions:
--   Open Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- Step 0: Create Schema & Grant Usage
CREATE SCHEMA IF NOT EXISTS system_history;
GRANT USAGE ON SCHEMA system_history TO anon, authenticated, service_role;

-- Step 1: Create Action_History Table in system_history schema
CREATE TABLE IF NOT EXISTS system_history."Action_History" (
    "LOG_ID"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    
    -- Who performed the action
    "STAFF_CODE"     BIGINT NULL,
    "STAFF_NAME"     TEXT NULL,
    "STAFF_ROLE"     TEXT NULL,
    
    -- What action was performed
    "ACTION_TYPE"    TEXT NOT NULL,
    "MODULE"         TEXT NOT NULL DEFAULT 'GENERAL',
    "DESCRIPTION"    TEXT NOT NULL,
    
    -- Target entity affected (e.g. ORDER, TABLE, MENU_ITEM, DISCOUNT)
    "TARGET_ENTITY"  TEXT NULL,
    "TARGET_ID"      TEXT NULL,
    
    -- State transitions & additional contextual metadata (JSONB)
    "PREVIOUS_STATE" JSONB NULL,
    "NEW_STATE"      JSONB NULL,
    "METADATA"       JSONB NULL DEFAULT '{}'::jsonb,
    
    -- When the action occurred
    "CREATED_AT"     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT "Action_History_pkey" PRIMARY KEY ("LOG_ID")
);

-- Step 2: Foreign Key Constraint to Staff_Codes (preserving history on delete)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_name = 'Staff_Codes' AND table_type = 'BASE TABLE'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint WHERE conname = 'action_history_staff_code_fkey'
    ) THEN
      ALTER TABLE system_history."Action_History"
        ADD CONSTRAINT action_history_staff_code_fkey
        FOREIGN KEY ("STAFF_CODE") REFERENCES public."Staff_Codes"("CODE_ID") ON DELETE SET NULL;
    END IF;
  ELSIF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'staff' AND table_name = 'Staff_Codes' AND table_type = 'BASE TABLE'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_constraint WHERE conname = 'action_history_staff_code_fkey'
    ) THEN
      ALTER TABLE system_history."Action_History"
        ADD CONSTRAINT action_history_staff_code_fkey
        FOREIGN KEY ("STAFF_CODE") REFERENCES staff."Staff_Codes"("CODE_ID") ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

-- Step 3: Performance Indexes
CREATE INDEX IF NOT EXISTS idx_action_history_created_at
    ON system_history."Action_History" ("CREATED_AT" DESC);

CREATE INDEX IF NOT EXISTS idx_action_history_staff_code
    ON system_history."Action_History" ("STAFF_CODE");

CREATE INDEX IF NOT EXISTS idx_action_history_action_type
    ON system_history."Action_History" ("ACTION_TYPE");

CREATE INDEX IF NOT EXISTS idx_action_history_module
    ON system_history."Action_History" ("MODULE");

CREATE INDEX IF NOT EXISTS idx_action_history_target
    ON system_history."Action_History" ("TARGET_ENTITY", "TARGET_ID");

CREATE INDEX IF NOT EXISTS idx_action_history_metadata_gin
    ON system_history."Action_History" USING gin ("METADATA");

-- Step 4: Table Grants & Permissions
GRANT ALL ON ALL TABLES IN SCHEMA system_history TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA system_history TO anon, authenticated, service_role;

-- Step 5: Row Level Security (RLS) Policies on underlying table
ALTER TABLE system_history."Action_History" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access to Action_History" ON system_history."Action_History";
CREATE POLICY "Allow read access to Action_History"
    ON system_history."Action_History" FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow insert to Action_History" ON system_history."Action_History";
CREATE POLICY "Allow insert to Action_History"
    ON system_history."Action_History" FOR INSERT
    WITH CHECK (true);

-- Step 6: Supabase Realtime Publication
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'system_history'
          AND tablename = 'Action_History'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE system_history."Action_History";
    END IF;
END $$;

-- Step 7: Public View for PostgREST / Supabase Client Access
-- Allows frontend `supabase.from('Action_History')` to work seamlessly.
CREATE OR REPLACE VIEW public."Action_History"
    WITH (security_invoker = on) AS 
    SELECT * FROM system_history."Action_History";

GRANT ALL ON public."Action_History" TO anon, authenticated, service_role;

-- Step 8: Helper Function to Log Actions (Auto-resolves Staff Name & Role if omitted)
CREATE OR REPLACE FUNCTION public.log_staff_action(
    p_staff_code BIGINT,
    p_action_type TEXT,
    p_description TEXT,
    p_module TEXT DEFAULT 'GENERAL',
    p_target_entity TEXT DEFAULT NULL,
    p_target_id TEXT DEFAULT NULL,
    p_staff_name TEXT DEFAULT NULL,
    p_staff_role TEXT DEFAULT NULL,
    p_previous_state JSONB DEFAULT NULL,
    p_new_state JSONB DEFAULT NULL,
    p_metadata JSONB DEFAULT '{}'::jsonb
) RETURNS BIGINT AS $$
DECLARE
    v_resolved_name TEXT := p_staff_name;
    v_resolved_role TEXT := p_staff_role;
    v_new_id BIGINT;
BEGIN
    -- Auto-resolve staff name and role from Staff_Codes if not explicitly passed
    IF p_staff_code IS NOT NULL AND (v_resolved_name IS NULL OR v_resolved_role IS NULL) THEN
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Staff_Codes') THEN
            SELECT "STAFF_NAME", "STAFF_ROLE"
            INTO v_resolved_name, v_resolved_role
            FROM public."Staff_Codes"
            WHERE "CODE_ID" = p_staff_code
            LIMIT 1;
        ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'staff' AND table_name = 'Staff_Codes') THEN
            SELECT "STAFF_NAME", "STAFF_ROLE"
            INTO v_resolved_name, v_resolved_role
            FROM staff."Staff_Codes"
            WHERE "CODE_ID" = p_staff_code
            LIMIT 1;
        END IF;
    END IF;

    INSERT INTO system_history."Action_History" (
        "STAFF_CODE",
        "STAFF_NAME",
        "STAFF_ROLE",
        "ACTION_TYPE",
        "MODULE",
        "DESCRIPTION",
        "TARGET_ENTITY",
        "TARGET_ID",
        "PREVIOUS_STATE",
        "NEW_STATE",
        "METADATA",
        "CREATED_AT"
    ) VALUES (
        p_staff_code,
        COALESCE(v_resolved_name, 'Unknown Staff'),
        COALESCE(v_resolved_role, 'STAFF'),
        p_action_type,
        COALESCE(p_module, 'GENERAL'),
        p_description,
        p_target_entity,
        p_target_id,
        p_previous_state,
        p_new_state,
        COALESCE(p_metadata, '{}'::jsonb),
        NOW()
    )
    RETURNING "LOG_ID" INTO v_new_id;

    RETURN v_new_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
