-- ==============================================================================
-- Migration 023: Cashier Shifts and Audit Logs
-- Schema: staff."Cashier_Shifts" and staff."Audit_Logs" + Public Views
--
-- Purpose:
--   Establishes persistent Cashier Operational Shift Sessions and comprehensive
--   Audit Logging. Fully separated from Supabase application authentication.
--   Enforces one active shift per cashier, tracks shift earnings & tables handled,
--   and maintains an append-only audit trail of financial and operational POS actions.
--
-- Instructions:
--   Open Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- Step 0: Ensure staff schema exists and has proper permissions
CREATE SCHEMA IF NOT EXISTS staff;
GRANT USAGE ON SCHEMA staff TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- Step 1: Create staff."Cashier_Shifts" Table
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff."Cashier_Shifts" (
    "SHIFT_ID"             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "STAFF_ID"             BIGINT NOT NULL,
    "STARTED_AT"           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "ENDED_AT"             TIMESTAMP WITH TIME ZONE NULL,
    "STATUS"               TEXT NOT NULL DEFAULT 'ACTIVE',
    "TOTAL_EARNING"        DOUBLE PRECISION NOT NULL DEFAULT 0,
    "TOTAL_TABLES_HANDLED" BIGINT NOT NULL DEFAULT 0,
    
    CONSTRAINT "Cashier_Shifts_pkey" PRIMARY KEY ("SHIFT_ID"),
    CONSTRAINT "cashier_shifts_status_check" CHECK (
        "STATUS" = ANY (ARRAY['ACTIVE'::text, 'ENDED'::text])
    )
);

-- Foreign Key to Staff_Codes (strictly references staff."Staff_Codes" base table)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'staff' AND table_name = 'Staff_Codes' AND table_type = 'BASE TABLE'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'cashier_shifts_staff_id_fkey'
        ) THEN
            ALTER TABLE staff."Cashier_Shifts"
                ADD CONSTRAINT cashier_shifts_staff_id_fkey
                FOREIGN KEY ("STAFF_ID") REFERENCES staff."Staff_Codes"("CODE_ID") ON DELETE RESTRICT;
        END IF;
    END IF;
END $$;

-- Enforce ONLY ONE active shift per staff member at the database level
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_shift_per_staff
    ON staff."Cashier_Shifts" ("STAFF_ID")
    WHERE ("STATUS" = 'ACTIVE');

-- Performance Indexes for Cashier_Shifts
CREATE INDEX IF NOT EXISTS idx_cashier_shifts_staff_id
    ON staff."Cashier_Shifts" ("STAFF_ID");

CREATE INDEX IF NOT EXISTS idx_cashier_shifts_status
    ON staff."Cashier_Shifts" ("STATUS");

CREATE INDEX IF NOT EXISTS idx_cashier_shifts_started_at
    ON staff."Cashier_Shifts" ("STARTED_AT" DESC);

-- ------------------------------------------------------------------------------
-- Step 2: Create staff."Audit_Logs" Table
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff."Audit_Logs" (
    "LOG_ID"       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SHIFT_ID"     BIGINT NULL,
    "STAFF_ID"     BIGINT NULL,
    "AUTH_USER_ID" TEXT NULL,
    "ACTION"       TEXT NOT NULL,
    "ENTITY_TYPE"  TEXT NULL,
    "ENTITY_ID"    TEXT NULL,
    "DESCRIPTION"  TEXT NULL,
    "METADATA"     JSONB NULL DEFAULT '{}'::jsonb,
    "CREATED_AT"   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT "Audit_Logs_pkey" PRIMARY KEY ("LOG_ID")
);

-- SHIFT_ID in Audit_Logs records events across Cashier_Shifts and Service_Shifts (no rigid FK to single table)
DO $$
BEGIN
    ALTER TABLE staff."Audit_Logs"
        DROP CONSTRAINT IF EXISTS audit_logs_shift_id_fkey;
END $$;

-- Foreign Key from Audit_Logs to Staff_Codes (strictly references staff."Staff_Codes" base table)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'staff' AND table_name = 'Staff_Codes' AND table_type = 'BASE TABLE'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'audit_logs_staff_id_fkey'
        ) THEN
            ALTER TABLE staff."Audit_Logs"
                ADD CONSTRAINT audit_logs_staff_id_fkey
                FOREIGN KEY ("STAFF_ID") REFERENCES staff."Staff_Codes"("CODE_ID") ON DELETE SET NULL;
        END IF;
    END IF;
END $$;

-- Performance Indexes for Audit_Logs
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
    ON staff."Audit_Logs" ("CREATED_AT" DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_staff_id
    ON staff."Audit_Logs" ("STAFF_ID");

CREATE INDEX IF NOT EXISTS idx_audit_logs_shift_id
    ON staff."Audit_Logs" ("SHIFT_ID");

CREATE INDEX IF NOT EXISTS idx_audit_logs_action
    ON staff."Audit_Logs" ("ACTION");

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity
    ON staff."Audit_Logs" ("ENTITY_TYPE", "ENTITY_ID");

CREATE INDEX IF NOT EXISTS idx_audit_logs_metadata_gin
    ON staff."Audit_Logs" USING gin ("METADATA");

-- ------------------------------------------------------------------------------
-- Step 3: Create Views (with security_invoker = on) for PostgREST / Client Access
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW public."Cashier_Shifts"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Cashier_Shifts";

CREATE OR REPLACE VIEW public."Audit_Logs"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Audit_Logs";

-- Synonym views for Cashier_Audit_Logs
CREATE OR REPLACE VIEW public."Cashier_Audit_Logs"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Audit_Logs";

CREATE OR REPLACE VIEW staff."Cashier_Audit_Logs"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Audit_Logs";

-- ------------------------------------------------------------------------------
-- Step 4: Table Grants & Permissions
-- ------------------------------------------------------------------------------
GRANT ALL ON TABLE staff."Cashier_Shifts" TO anon, authenticated, service_role;
GRANT ALL ON TABLE staff."Audit_Logs" TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA staff TO anon, authenticated, service_role;

GRANT ALL ON public."Cashier_Shifts" TO anon, authenticated, service_role;
GRANT ALL ON public."Audit_Logs" TO anon, authenticated, service_role;
GRANT ALL ON public."Cashier_Audit_Logs" TO anon, authenticated, service_role;
GRANT ALL ON staff."Cashier_Audit_Logs" TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- Step 5: Row Level Security (RLS) Policies
-- ------------------------------------------------------------------------------
ALTER TABLE staff."Cashier_Shifts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff."Audit_Logs" ENABLE ROW LEVEL SECURITY;

-- Cashier_Shifts RLS Policies
DROP POLICY IF EXISTS "Allow select Cashier_Shifts" ON staff."Cashier_Shifts";
CREATE POLICY "Allow select Cashier_Shifts"
    ON staff."Cashier_Shifts" FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow insert Cashier_Shifts" ON staff."Cashier_Shifts";
CREATE POLICY "Allow insert Cashier_Shifts"
    ON staff."Cashier_Shifts" FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update Cashier_Shifts" ON staff."Cashier_Shifts";
CREATE POLICY "Allow update Cashier_Shifts"
    ON staff."Cashier_Shifts" FOR UPDATE
    USING (true);

-- Audit_Logs RLS Policies (Append-only for regular operations)
DROP POLICY IF EXISTS "Allow select Audit_Logs" ON staff."Audit_Logs";
CREATE POLICY "Allow select Audit_Logs"
    ON staff."Audit_Logs" FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow insert Audit_Logs" ON staff."Audit_Logs";
CREATE POLICY "Allow insert Audit_Logs"
    ON staff."Audit_Logs" FOR INSERT
    WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- Step 6: Supabase Realtime Publications
-- ------------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'staff'
          AND tablename = 'Cashier_Shifts'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE staff."Cashier_Shifts";
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'staff'
          AND tablename = 'Audit_Logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE staff."Audit_Logs";
    END IF;
END $$;
