-- ==============================================================================
-- Migration 024: Service Shifts for Service Interface
-- Schema: staff."Service_Shifts" + Public View
--
-- Purpose:
--   Establishes persistent Service Operational Shift Sessions for floor staff,
--   servers, and waiters operating the Service Interface (/service).
--   Completely independent of the Cashier Shift system and Supabase Auth.
--   Enforces one active service shift per staff member, tracks orders punched
--   and tables served, with full append-only audit trail logging.
--
-- Instructions:
--   Open Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- Step 0: Ensure staff schema exists and has proper permissions
CREATE SCHEMA IF NOT EXISTS staff;
GRANT USAGE ON SCHEMA staff TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- Step 1: Create staff."Service_Shifts" Table
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff."Service_Shifts" (
    "SHIFT_ID"             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "STAFF_ID"             BIGINT NOT NULL,
    "STARTED_AT"           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "ENDED_AT"             TIMESTAMP WITH TIME ZONE NULL,
    "STATUS"               TEXT NOT NULL DEFAULT 'ACTIVE',
    "TOTAL_ORDERS_PUNCHED" BIGINT NOT NULL DEFAULT 0,
    "TOTAL_TABLES_SERVED"  BIGINT NOT NULL DEFAULT 0,
    
    CONSTRAINT "Service_Shifts_pkey" PRIMARY KEY ("SHIFT_ID"),
    CONSTRAINT "service_shifts_status_check" CHECK (
        "STATUS" = ANY (ARRAY['ACTIVE'::text, 'ENDED'::text])
    )
);

-- Foreign Key to Staff_Codes (strictly references staff."Staff_Codes" base table)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'staff' AND table_name = 'Staff_Codes' AND table_type = 'BASE TABLE'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'service_shifts_staff_id_fkey'
        ) THEN
            ALTER TABLE staff."Service_Shifts"
                ADD CONSTRAINT service_shifts_staff_id_fkey
                FOREIGN KEY ("STAFF_ID") REFERENCES staff."Staff_Codes"("CODE_ID") ON DELETE RESTRICT;
        END IF;
    END IF;
END $$;

-- Enforce ONLY ONE active service shift per staff member
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_service_shift_per_staff
    ON staff."Service_Shifts" ("STAFF_ID")
    WHERE ("STATUS" = 'ACTIVE');

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_service_shifts_staff_id
    ON staff."Service_Shifts" ("STAFF_ID");

CREATE INDEX IF NOT EXISTS idx_service_shifts_status
    ON staff."Service_Shifts" ("STATUS");

CREATE INDEX IF NOT EXISTS idx_service_shifts_started_at
    ON staff."Service_Shifts" ("STARTED_AT" DESC);

-- ------------------------------------------------------------------------------
-- Step 2: Create Public View (with security_invoker = on) for PostgREST Access
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW public."Service_Shifts"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Service_Shifts";

-- ------------------------------------------------------------------------------
-- Step 3: Table Grants & Permissions
-- ------------------------------------------------------------------------------
GRANT ALL ON TABLE staff."Service_Shifts" TO anon, authenticated, service_role;
GRANT ALL ON public."Service_Shifts" TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- Step 4: Row Level Security (RLS) Policies
-- ------------------------------------------------------------------------------
ALTER TABLE staff."Service_Shifts" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select Service_Shifts" ON staff."Service_Shifts";
CREATE POLICY "Allow select Service_Shifts"
    ON staff."Service_Shifts" FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow insert Service_Shifts" ON staff."Service_Shifts";
CREATE POLICY "Allow insert Service_Shifts"
    ON staff."Service_Shifts" FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update Service_Shifts" ON staff."Service_Shifts";
CREATE POLICY "Allow update Service_Shifts"
    ON staff."Service_Shifts" FOR UPDATE
    USING (true);

-- ------------------------------------------------------------------------------
-- Step 5: Supabase Realtime Publication
-- ------------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'staff'
          AND tablename = 'Service_Shifts'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE staff."Service_Shifts";
    END IF;
END $$;
