-- ==============================================================================
-- Migration 025: Business Day Management, Cashier Transactions, and Daily Summary
-- Schemas:
--   - staff."Business_Days" (Base Table)
--   - staff."Cashier_Shifts", staff."Service_Shifts", staff."Audit_Logs"
--   - system_history."Completed_Orders" (Base Table)
--   - orders."Restaurant_Orders" (Base Table)
--   - Public Views with security_invoker = on for PostgREST access
--
-- Purpose:
--   1. Establishes the persistent Business Day table (staff."Business_Days")
--      controlling whether POS interfaces are permitted to accept transactions.
--   2. Enforces that at most ONE business day may be active ('OPEN') at any time.
--   3. Associates Cashier Shifts, Service Shifts, Audit Logs, and Completed Orders
--      with the active BUSINESS_DAY_ID via foreign keys on base tables in domain schemas.
--   4. Provides race-condition-free database functions for Start Day and End Day,
--      preventing Start/End Day if unresolved active orders exist in orders."Restaurant_Orders".
--   5. Tracks per-cashier transaction attribution and provides daily summary aggregates
--      directly from system_history."Completed_Orders".
--
-- Instructions:
--   Open Supabase Dashboard -> SQL Editor -> New Query -> Paste & Run
-- ==============================================================================

-- Step 0: Ensure schemas exist and permissions are granted
CREATE SCHEMA IF NOT EXISTS staff;
CREATE SCHEMA IF NOT EXISTS system_history;
CREATE SCHEMA IF NOT EXISTS orders;

GRANT USAGE ON SCHEMA staff TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA system_history TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA orders TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- Step 1: Create staff."Business_Days" Table
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff."Business_Days" (
    "BUSINESS_DAY_ID"        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BUSINESS_DATE"          DATE NOT NULL DEFAULT CURRENT_DATE,
    "STATUS"                 TEXT NOT NULL DEFAULT 'OPEN',
    "STARTED_AT"             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "STARTED_BY"             TEXT NULL,
    "ENDED_AT"               TIMESTAMP WITH TIME ZONE NULL,
    "ENDED_BY"               TEXT NULL,
    "TOTAL_TRANSACTIONS"     BIGINT NOT NULL DEFAULT 0,
    "TOTAL_REVENUE"          DOUBLE PRECISION NOT NULL DEFAULT 0,
    "TOTAL_CUSTOMERS_SERVED" BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT "Business_Days_pkey" PRIMARY KEY ("BUSINESS_DAY_ID"),
    CONSTRAINT "business_days_status_check" CHECK (
        "STATUS" = ANY (ARRAY['OPEN'::text, 'CLOSED'::text])
    )
);

-- Enforce ONLY ONE open business day at any time
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_open_business_day
    ON staff."Business_Days" ("STATUS")
    WHERE ("STATUS" = 'OPEN');

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_business_days_date
    ON staff."Business_Days" ("BUSINESS_DATE" DESC);

CREATE INDEX IF NOT EXISTS idx_business_days_started_at
    ON staff."Business_Days" ("STARTED_AT" DESC);

-- ------------------------------------------------------------------------------
-- Step 2: Create Public View (with security_invoker = on) for PostgREST Access
-- ------------------------------------------------------------------------------
CREATE OR REPLACE VIEW public."Business_Days"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Business_Days";

-- ------------------------------------------------------------------------------
-- Step 3: Add BUSINESS_DAY_ID and Attribution Columns to Domain Tables
-- ------------------------------------------------------------------------------

-- 3a. Add to staff."Cashier_Shifts"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'staff' AND table_name = 'Cashier_Shifts' AND table_type = 'BASE TABLE'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'staff' AND table_name = 'Cashier_Shifts' AND column_name = 'BUSINESS_DAY_ID'
        ) THEN
            ALTER TABLE staff."Cashier_Shifts"
                ADD COLUMN "BUSINESS_DAY_ID" BIGINT NULL REFERENCES staff."Business_Days"("BUSINESS_DAY_ID") ON DELETE SET NULL;
            CREATE INDEX IF NOT EXISTS idx_cashier_shifts_business_day_id
                ON staff."Cashier_Shifts" ("BUSINESS_DAY_ID");
        END IF;
    END IF;
END $$;

-- 3b. Add to staff."Service_Shifts"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'staff' AND table_name = 'Service_Shifts' AND table_type = 'BASE TABLE'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'staff' AND table_name = 'Service_Shifts' AND column_name = 'BUSINESS_DAY_ID'
        ) THEN
            ALTER TABLE staff."Service_Shifts"
                ADD COLUMN "BUSINESS_DAY_ID" BIGINT NULL REFERENCES staff."Business_Days"("BUSINESS_DAY_ID") ON DELETE SET NULL;
            CREATE INDEX IF NOT EXISTS idx_service_shifts_business_day_id
                ON staff."Service_Shifts" ("BUSINESS_DAY_ID");
        END IF;
    END IF;
END $$;

-- 3c. Add to staff."Audit_Logs"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'staff' AND table_name = 'Audit_Logs' AND table_type = 'BASE TABLE'
    ) THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'staff' AND table_name = 'Audit_Logs' AND column_name = 'BUSINESS_DAY_ID'
        ) THEN
            ALTER TABLE staff."Audit_Logs"
                ADD COLUMN "BUSINESS_DAY_ID" BIGINT NULL REFERENCES staff."Business_Days"("BUSINESS_DAY_ID") ON DELETE SET NULL;
            CREATE INDEX IF NOT EXISTS idx_audit_logs_business_day_id
                ON staff."Audit_Logs" ("BUSINESS_DAY_ID");
        END IF;

        -- Drop restrictive shift_id foreign key because Audit_Logs logs both Cashier_Shifts and Service_Shifts
        ALTER TABLE staff."Audit_Logs"
            DROP CONSTRAINT IF EXISTS audit_logs_shift_id_fkey;
    END IF;
END $$;

-- Refresh public view for Audit_Logs to expose newly added columns to PostgREST
CREATE OR REPLACE VIEW public."Audit_Logs"
    WITH (security_invoker = on) AS
    SELECT * FROM staff."Audit_Logs";

-- 3d. Add Attribution to system_history."Completed_Orders" (Base Table)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'system_history' AND table_name = 'Completed_Orders' AND table_type = 'BASE TABLE'
    ) THEN
        -- Add columns if not present
        ALTER TABLE system_history."Completed_Orders"
            ADD COLUMN IF NOT EXISTS "BUSINESS_DAY_ID" BIGINT NULL,
            ADD COLUMN IF NOT EXISTS "SHIFT_ID" BIGINT NULL,
            ADD COLUMN IF NOT EXISTS "STAFF_ID" BIGINT NULL,
            ADD COLUMN IF NOT EXISTS "CASHIER_NAME" TEXT NULL;

        -- Foreign Key to Business_Days
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'completed_orders_business_day_id_fkey'
        ) THEN
            ALTER TABLE system_history."Completed_Orders"
                ADD CONSTRAINT completed_orders_business_day_id_fkey
                FOREIGN KEY ("BUSINESS_DAY_ID") REFERENCES staff."Business_Days"("BUSINESS_DAY_ID") ON DELETE SET NULL;
        END IF;

        -- Drop restrictive shift_id foreign key because Completed_Orders records orders from Cashier_Shifts or Service_Shifts
        ALTER TABLE system_history."Completed_Orders"
            DROP CONSTRAINT IF EXISTS completed_orders_shift_id_fkey;

        -- Foreign Key to Staff_Codes
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'completed_orders_staff_id_fkey'
        ) THEN
            ALTER TABLE system_history."Completed_Orders"
                ADD CONSTRAINT completed_orders_staff_id_fkey
                FOREIGN KEY ("STAFF_ID") REFERENCES staff."Staff_Codes"("CODE_ID") ON DELETE SET NULL;
        END IF;

        -- Performance Indexes
        CREATE INDEX IF NOT EXISTS idx_completed_orders_business_day_id
            ON system_history."Completed_Orders" ("BUSINESS_DAY_ID");

        CREATE INDEX IF NOT EXISTS idx_completed_orders_staff_id
            ON system_history."Completed_Orders" ("STAFF_ID");

        CREATE INDEX IF NOT EXISTS idx_completed_orders_shift_id
            ON system_history."Completed_Orders" ("SHIFT_ID");
    END IF;
END $$;

-- Refresh public view for Completed_Orders to expose newly added columns to PostgREST
CREATE OR REPLACE VIEW public."Completed_Orders"
    WITH (security_invoker = on) AS
    SELECT * FROM system_history."Completed_Orders";

-- 3e. Add Attribution to orders."Restaurant_Orders" (Base Table)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'orders' AND table_name = 'Restaurant_Orders' AND table_type = 'BASE TABLE'
    ) THEN
        ALTER TABLE orders."Restaurant_Orders"
            ADD COLUMN IF NOT EXISTS "BUSINESS_DAY_ID" BIGINT NULL,
            ADD COLUMN IF NOT EXISTS "SHIFT_ID" BIGINT NULL,
            ADD COLUMN IF NOT EXISTS "STAFF_ID" BIGINT NULL;

        -- Foreign Key to Business_Days
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'restaurant_orders_business_day_id_fkey'
        ) THEN
            ALTER TABLE orders."Restaurant_Orders"
                ADD CONSTRAINT restaurant_orders_business_day_id_fkey
                FOREIGN KEY ("BUSINESS_DAY_ID") REFERENCES staff."Business_Days"("BUSINESS_DAY_ID") ON DELETE SET NULL;
        END IF;

        -- Drop restrictive shift_id foreign key because Restaurant_Orders records orders from Cashier_Shifts or Service_Shifts
        ALTER TABLE orders."Restaurant_Orders"
            DROP CONSTRAINT IF EXISTS restaurant_orders_shift_id_fkey;

        -- Foreign Key to Staff_Codes
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'restaurant_orders_staff_id_fkey'
        ) THEN
            ALTER TABLE orders."Restaurant_Orders"
                ADD CONSTRAINT restaurant_orders_staff_id_fkey
                FOREIGN KEY ("STAFF_ID") REFERENCES staff."Staff_Codes"("CODE_ID") ON DELETE SET NULL;
        END IF;

        CREATE INDEX IF NOT EXISTS idx_restaurant_orders_business_day_id
            ON orders."Restaurant_Orders" ("BUSINESS_DAY_ID");
    END IF;
END $$;

-- Refresh public view for Restaurant_Orders to expose newly added columns to PostgREST
CREATE OR REPLACE VIEW public."Restaurant_Orders"
    WITH (security_invoker = on) AS
    SELECT * FROM orders."Restaurant_Orders";

-- ------------------------------------------------------------------------------
-- Step 4: Table Grants & Permissions
-- ------------------------------------------------------------------------------
GRANT ALL ON TABLE staff."Business_Days" TO anon, authenticated, service_role;
GRANT ALL ON public."Business_Days" TO anon, authenticated, service_role;
GRANT ALL ON public."Completed_Orders" TO anon, authenticated, service_role;
GRANT ALL ON public."Restaurant_Orders" TO anon, authenticated, service_role;

-- ------------------------------------------------------------------------------
-- Step 5: Row Level Security (RLS) Policies
-- ------------------------------------------------------------------------------
ALTER TABLE staff."Business_Days" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow select Business_Days" ON staff."Business_Days";
CREATE POLICY "Allow select Business_Days"
    ON staff."Business_Days" FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Allow insert Business_Days" ON staff."Business_Days";
CREATE POLICY "Allow insert Business_Days"
    ON staff."Business_Days" FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow update Business_Days" ON staff."Business_Days";
CREATE POLICY "Allow update Business_Days"
    ON staff."Business_Days" FOR UPDATE
    USING (true);

-- ------------------------------------------------------------------------------
-- Step 6: Realtime Publication
-- ------------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'staff'
          AND tablename = 'Business_Days'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE staff."Business_Days";
    END IF;
END $$;

-- ------------------------------------------------------------------------------
-- Step 7: Transaction-Safe Stored Procedures for Start Day & End Day
-- ------------------------------------------------------------------------------

-- Function to start business day safely in schema staff
CREATE OR REPLACE FUNCTION staff.start_business_day(
    p_started_by TEXT,
    p_business_date DATE DEFAULT CURRENT_DATE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_open_count INT;
    v_active_orders INT := 0;
    v_new_id BIGINT;
    v_row staff."Business_Days"%ROWTYPE;
BEGIN
    -- 1. Check if an open business day already exists
    SELECT COUNT(*) INTO v_open_count
    FROM staff."Business_Days"
    WHERE "STATUS" = 'OPEN';

    IF v_open_count > 0 THEN
        RAISE EXCEPTION 'A business day is already open. Please conclude the active day before starting a new one.';
    END IF;

    -- 2. Check if active orders exist in orders."Restaurant_Orders" base table
    BEGIN
        SELECT COUNT(*) INTO v_active_orders
        FROM orders."Restaurant_Orders"
        WHERE "ORDER_STATUS" IN ('REQUESTED', 'VERIFIED', 'PREPARING', 'READY', 'SERVED');
    EXCEPTION WHEN OTHERS THEN
        v_active_orders := 0;
    END;

    IF v_active_orders > 0 THEN
        RAISE EXCEPTION 'Cannot start business day: % active order(s) exist. All active orders must be completed or cancelled before opening a new day.', v_active_orders;
    END IF;

    -- 3. Insert new open Business Day
    INSERT INTO staff."Business_Days" (
        "BUSINESS_DATE",
        "STATUS",
        "STARTED_AT",
        "STARTED_BY"
    ) VALUES (
        COALESCE(p_business_date, CURRENT_DATE),
        'OPEN',
        NOW(),
        p_started_by
    )
    RETURNING * INTO v_row;

    RETURN to_jsonb(v_row);
END;
$$;

-- Function to end business day safely in schema staff
CREATE OR REPLACE FUNCTION staff.end_business_day(
    p_ended_by TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_active_day staff."Business_Days"%ROWTYPE;
    v_active_orders INT := 0;
    v_active_cashier_shifts INT := 0;
    v_active_service_shifts INT := 0;
    v_total_tx BIGINT := 0;
    v_total_rev DOUBLE PRECISION := 0;
    v_total_cust BIGINT := 0;
BEGIN
    -- 1. Retrieve the active business day
    SELECT * INTO v_active_day
    FROM staff."Business_Days"
    WHERE "STATUS" = 'OPEN'
    LIMIT 1;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No open business day found to conclude.';
    END IF;

    -- 2. Verify no active orders exist in orders."Restaurant_Orders"
    BEGIN
        SELECT COUNT(*) INTO v_active_orders
        FROM orders."Restaurant_Orders"
        WHERE "ORDER_STATUS" IN ('REQUESTED', 'VERIFIED', 'PREPARING', 'READY', 'SERVED');
    EXCEPTION WHEN OTHERS THEN
        v_active_orders := 0;
    END;

    IF v_active_orders > 0 THEN
        RAISE EXCEPTION 'Cannot end business day: % active order(s) still exist. Please settle or cancel all orders before concluding the day.', v_active_orders;
    END IF;

    -- 3. Verify no active cashier shifts exist
    BEGIN
        SELECT COUNT(*) INTO v_active_cashier_shifts
        FROM staff."Cashier_Shifts"
        WHERE "STATUS" = 'ACTIVE';
    EXCEPTION WHEN OTHERS THEN
        v_active_cashier_shifts := 0;
    END;

    IF v_active_cashier_shifts > 0 THEN
        RAISE EXCEPTION 'Cannot end business day: % active cashier shift(s) exist. All cashiers must conclude their shifts first.', v_active_cashier_shifts;
    END IF;

    -- 4. Verify no active service shifts exist
    BEGIN
        SELECT COUNT(*) INTO v_active_service_shifts
        FROM staff."Service_Shifts"
        WHERE "STATUS" = 'ACTIVE';
    EXCEPTION WHEN OTHERS THEN
        v_active_service_shifts := 0;
    END;

    IF v_active_service_shifts > 0 THEN
        RAISE EXCEPTION 'Cannot end business day: % active service shift(s) exist. All floor staff must conclude their shifts first.', v_active_service_shifts;
    END IF;

    -- 5. Calculate daily metrics directly from system_history."Completed_Orders" during this business day
    BEGIN
        SELECT
            COUNT(*),
            COALESCE(SUM("TOTAL_BILL"), 0),
            COALESCE(SUM("GUEST_COUNT"), 0)
        INTO
            v_total_tx,
            v_total_rev,
            v_total_cust
        FROM system_history."Completed_Orders"
        WHERE ("BUSINESS_DAY_ID" = v_active_day."BUSINESS_DAY_ID"
               OR ("COMPLETED_AT" >= v_active_day."STARTED_AT" AND v_active_day."BUSINESS_DAY_ID" IS NOT NULL));
    EXCEPTION WHEN OTHERS THEN
        NULL;
    END;

    -- 6. Update the business day to CLOSED
    UPDATE staff."Business_Days"
    SET "STATUS" = 'CLOSED',
        "ENDED_AT" = NOW(),
        "ENDED_BY" = p_ended_by,
        "TOTAL_TRANSACTIONS" = v_total_tx,
        "TOTAL_REVENUE" = v_total_rev,
        "TOTAL_CUSTOMERS_SERVED" = v_total_cust
    WHERE "BUSINESS_DAY_ID" = v_active_day."BUSINESS_DAY_ID"
    RETURNING * INTO v_active_day;

    RETURN to_jsonb(v_active_day);
END;
$$;

-- ------------------------------------------------------------------------------
-- Step 8: Public Stored Procedure Wrappers for Default Supabase PostgREST RPC
-- ------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.start_business_day(
    p_started_by TEXT,
    p_business_date DATE DEFAULT CURRENT_DATE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN staff.start_business_day(p_started_by, p_business_date);
END;
$$;

CREATE OR REPLACE FUNCTION public.end_business_day(
    p_ended_by TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN staff.end_business_day(p_ended_by);
END;
$$;

-- Grant execution to roles
GRANT EXECUTE ON FUNCTION staff.start_business_day TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION staff.end_business_day TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.start_business_day TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.end_business_day TO anon, authenticated, service_role;
